"""Diagnostic quiz questions, batch C: Modules 13-18 in Databases course.

Each entry is (title, code, symptom, questions, answer).
"""

from __future__ import annotations

DIAGNOSTICS: dict[str, list[tuple[str, str, str, list[str], str]]] = {'13': [("CROSSSLOT Keys in Request Don't Hash to the Same Slot",
         '# Redis Cluster Python Client\n'
         'import rediscluster\n'
         '\n'
         'rc = rediscluster.RedisCluster(host="redis-cluster.internal", port=7000)\n'
         '\n'
         'def transfer_points(from_user: str, to_user: str, amount: int):\n'
         '    # Multi-key pipeline to transfer loyalty points\n'
         '    pipe = rc.pipeline()\n'
         '    pipe.decrby(f"user:{from_user}:balance", amount)\n'
         '    pipe.incrby(f"user:{to_user}:balance", amount)\n'
         '    pipe.execute()\n'
         '\n'
         'transfer_points("alice_99", "bob_102", 50)\n',
         "redis.exceptions.RedisClusterException: CROSSSLOT Keys in request don't hash to the same slot when executing "
         'pipeline.',
         ['Why does Redis Cluster reject multi-key commands or pipelines containing keys from different users?',
          'How does Redis Cluster compute key-to-slot mapping, and how can you check which slot each key maps to?',
          'How do hash tags (`{...}`) solve this issue, and what is the trade-off of clustering keys into the same '
          'hash slot?'],
         '**Root Cause:**\n'
         'Redis Cluster partitions its 16,384 hash slots across primary nodes. Multi-key operations (transactions, '
         'MGET/MSET, or transactional pipelines) are strictly constrained to keys that map to the exact same hash slot '
         'on the exact same primary node. `user:alice_99:balance` hashes to CRC16("user:alice_99:balance") % 16384, '
         'whereas `user:bob_102:balance` hashes to a completely different slot located on a different master node.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. In `redis-cli`:\n'
         '   ```bash\n'
         '   CLUSTER KEYSLOT "user:alice_99:balance"   # e.g. slot 11422 (Node A)\n'
         '   CLUSTER KEYSLOT "user:bob_102:balance"     # e.g. slot 4819 (Node B)\n'
         '   ```\n'
         '2. Verify node slot assignments:\n'
         '   ```bash\n'
         '   CLUSTER NODES\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '- **Approach 1 (Hash Tags):** If two keys must reside on the same slot, enclose the common grouping token in '
         'braces `{...}`:\n'
         '  ```python\n'
         "  # Both keys will hash based ONLY on the string inside '{tenant_42}'\n"
         '  key1 = "{tenant_42}:user:alice:balance"\n'
         '  key2 = "{tenant_42}:user:bob:balance"\n'
         '  ```\n'
         '- **Approach 2 (Distributed Workflows):** If keys naturally belong to separate entities across the cluster, '
         'do not execute multi-key single-node pipelines. Instead, use a two-phase application workflow, or execute '
         'two separate single-key calls with idempotency keys and compensating transactions (Saga pattern). Beware '
         'that overusing hash tags can create hot shards if too many keys hash to one node.'),
        ('Redis Sentinel Split-Brain and Dual-Master Write Loss',
         '# redis.conf on Primary (Node 1)\n'
         'bind 0.0.0.0\n'
         'port 6379\n'
         '# min-replicas-to-write commented out (default 0)\n'
         '# min-replicas-max-lag commented out (default 10)\n'
         '\n'
         '# Sentinel configuration on 3 nodes\n'
         'sentinel monitor mymaster 10.0.1.10 6379 2\n'
         'sentinel down-after-milliseconds mymaster 5000\n'
         'sentinel failover-timeout mymaster 15000\n',
         'During a 20-second network partition between datacenter rack A and B, Node 1 continued accepting writes from '
         'client partition A. Sentinel in partition B elected Node 2 as new master. Once network healed, 15,000 writes '
         'sent to Node 1 vanished completely.',
         ['What caused the silent loss of 15,000 committed writes when the network partition healed?',
          'What command and log entries on Node 1 confirm that it underwent full resynchronization and discarded its '
          'dataset?',
          'How do `min-replicas-to-write` and `min-replicas-max-lag` guard against split-brain write loss?'],
         '**Root Cause:**\n'
         'Redis replication is asynchronous. During the partition, Node 1 was isolated from Sentinels and replicas in '
         'partition B, but still reachable by local clients in partition A. Sentinel formed a quorum in partition B '
         'and promoted Node 2. When the partition healed, Sentinels reconfigured Node 1 to become a replica of Node 2. '
         'When a replica connects to a new master, it empties its entire local database (`FLUSHALL`) and performs a '
         'full resync (RDB snapshot load) from Node 2, completely erasing all writes committed to Node 1 during the '
         'partition.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check Redis logs on Node 1:\n'
         '   ```text\n'
         '   [Sentinel] +convert-to-slave master mymaster 10.0.1.10 6379 ...\n'
         '   [Replication] Connecting to MASTER 10.0.2.20:6379\n'
         '   [Replication] MASTER <-> REPLICA sync: Flush old data from memory\n'
         '   ```\n'
         '2. Check replication lag on replica:\n'
         '   ```bash\n'
         '   redis-cli -h node1 INFO replication\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         'Enforce write fencing using replica acknowledgments in `redis.conf`:\n'
         '```conf\n'
         '# Reject writes if fewer than 1 healthy replica acknowledge lag <= 10s\n'
         'min-replicas-to-write 1\n'
         'min-replicas-max-lag 10\n'
         '```\n'
         'When Node 1 loses connection to all replicas, it immediately responds with `(error) NOREPLICAS Not enough '
         'good replicas to write` to local clients, preventing writes to the partitioned master.'),
        ('Lua Script Blocking Redis Single-Thread Event Loop',
         '-- Lua script executed via EVALSHA\n'
         "local keys = redis.call('KEYS', 'session:user:*')\n"
         'local expired = 0\n'
         'for i, k in ipairs(keys) do\n'
         "    local ttl = redis.call('TTL', k)\n"
         '    if ttl == -1 then\n'
         "        redis.call('DEL', k)\n"
         '        expired = expired + 1\n'
         '    end\n'
         'end\n'
         'return expired\n',
         'All incoming Redis client requests across all microservices time out with connection drops. Redis latency '
         "spikes from 0.8ms to 15,000ms. Clients attempting to connect receive '(error) BUSY Redis is busy running a "
         "script'.",
         ['Why does this Lua script freeze all other Redis commands on the server?',
          'How can you detect running scripts and safely kill or inspect a frozen Lua script?',
          'How should this key-cleanup routine be refactored using SCAN and batched execution?'],
         '**Root Cause:**\n'
         'Redis is fundamentally single-threaded for command execution. Lua scripts in Redis execute atomically and '
         'exclusively: while a script is running, no other client command or event loop iteration can proceed. Running '
         "`redis.call('KEYS', ...)` on millions of keys scans the entire keyspace in $O(N)$ time in memory inside the "
         'Lua VM, blocking all other connections. After `lua-time-limit` (default 5s), Redis starts replying with '
         '`BUSY`.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check slowlog:\n'
         '   ```bash\n'
         '   redis-cli SLOWLOG GET 10\n'
         '   ```\n'
         '2. Check if a script is currently running:\n'
         '   ```bash\n'
         '   redis-cli SCRIPT KILL    # Only succeeds if script has not issued write commands\n'
         '   # If write commands have been issued, redis requires:\n'
         '   redis-cli SHUTDOWN NOSAVE\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. Never run `KEYS` inside Lua or production.\n'
         '2. Perform cursor-based iteration outside of Lua using `SCAN` in Python in batches of 500:\n'
         '   ```python\n'
         '   cursor = 0\n'
         '   while True:\n'
         '       cursor, keys = r.scan(cursor=cursor, match="session:user:*", count=500)\n'
         '       if keys:\n'
         '           # Check TTL or delete in small pipelines\n'
         '           pipe = r.pipeline(transaction=False)\n'
         '           for k in keys:\n'
         '               pipe.ttl(k)\n'
         '           ttls = pipe.execute()\n'
         '           to_del = [k for k, ttl in zip(keys, ttls) if ttl == -1]\n'
         '           if to_del:\n'
         '               r.delete(*to_del)\n'
         '       if cursor == 0:\n'
         '           break\n'
         '   ```'),
        ('Redis Cluster Slot Migration MOVED vs ASK Loop',
         'import redis\n'
         '# Using standard redis-py instead of redis-py-cluster / redis.cluster\n'
         'client = redis.Redis(host="node1.cluster.internal", port=7000)\n'
         '\n'
         '# Resharding slot 5460 from Node 1 to Node 2 is 40% complete\n'
         'response = client.get("account:user_8821")\n',
         'Client throws redis.exceptions.ResponseError: ASK 5460 10.0.1.12:7000 and crashes instead of returning the '
         'requested user data.',
         ['What is the difference between a `MOVED` redirection and an `ASK` redirection in Redis Cluster?',
          'What exact two-step sequence must a client execute upon receiving an `ASK` redirection?',
          'Why did using a non-cluster-aware client library cause this error, and how should it be resolved?'],
         '**Root Cause:**\n'
         'During online resharding / slot migration in Redis Cluster:\n'
         '- `MOVED 5460 10.0.1.12:7000` means slot 5460 permanently belongs to Node 2. The client must update its '
         'internal slot routing table.\n'
         '- `ASK 5460 10.0.1.12:7000` is transient: slot 5460 is currently migrating. Some keys are still on Node 1, '
         'but the requested key has already been moved to Node 2. The client must query Node 2 *for this request only* '
         'without updating its permanent slot routing map.\n'
         'A non-cluster-aware client does not parse cluster redirections and raises `ResponseError`.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check migration state in `redis-cli`:\n'
         '   ```bash\n'
         '   CLUSTER NODES | grep -E "importing|migrating"\n'
         '   ```\n'
         '2. Check key location:\n'
         '   ```bash\n'
         '   redis-cli -h 10.0.1.11 -p 7000 CLUSTER KEYSLOT account:user_8821\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. Switch to a cluster-aware client (`redis.cluster.RedisCluster` in `redis-py >= 4.1`):\n'
         '   ```python\n'
         '   from redis.cluster import RedisCluster\n'
         '   rc = RedisCluster(host="node1.cluster.internal", port=7000)\n'
         '   val = rc.get("account:user_8821")  # Transparently handles MOVED and ASK\n'
         '   ```\n'
         '2. The protocol handshake executed automatically by cluster clients on `ASK`:\n'
         '   - Connect to target node (`10.0.1.12:7000`)\n'
         '   - Send `ASKING` command\n'
         '   - Send the target command: `GET account:user_8821`'),
        ('Pub/Sub Slow Consumer Client Output Buffer Overflow',
         '# redis.conf\n'
         'client-output-buffer-limit pubsub 32mb 8mb 60\n'
         '# hard limit 32MB, soft limit 8MB for 60 seconds\n'
         '\n'
         '# Python subscriber running data analysis\n'
         'sub = r.pubsub()\n'
         'sub.subscribe("market_ticks_high_frequency")\n'
         'for message in sub.listen():\n'
         '    time.sleep(0.05)  # Heavy NumPy processing per tick (20 msgs/sec throughput)\n'
         '    # Publisher emits 2,000 ticks/sec\n',
         'The subscriber process abruptly disconnects after ~45 seconds with ConnectionResetError: [Errno 104] '
         "Connection reset by peer. Redis server logs: 'Client id=4821 scheduled to be closed ASAP for overcoming of "
         "output buffer limits'.",
         ['Why does Redis forcefully terminate the connection of this subscriber?',
          'Which Redis commands allow monitoring of client buffer consumption and identifying slow consumers?',
          'What architectural pattern should replace Pub/Sub when message consumers require processing time or '
          'backpressure?'],
         '**Root Cause:**\n'
         'Redis Pub/Sub has no server-side persistence or backpressure. Published messages are immediately queued into '
         "each subscriber's client output buffer in Redis memory. When publisher rate (2,000 msgs/sec) drastically "
         "outpaces consumer processing (20 msgs/sec), the subscriber's outbound buffer balloons. Once it breaches the "
         'hard limit (32MB) or soft limit (8MB continuously for 60s), Redis disconnects the subscriber to protect '
         'itself from Out-Of-Memory (OOM) crashes.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check client list in `redis-cli`:\n'
         '   ```bash\n'
         '   redis-cli CLIENT LIST\n'
         "   # Look for high 'omem' (output memory) and 'obl' / 'oll' (output buffer/list length)\n"
         '   ```\n'
         '2. Check memory usage by clients:\n'
         '   ```bash\n'
         '   redis-cli INFO memory | grep mem_clients_normal\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. Migrate from Pub/Sub to **Redis Streams** (`XADD`, `XREADGROUP`, `XACK`). Redis Streams store messages in '
         'a bounded stream (`MAXLEN ~ 100000`) with consumer groups, enabling worker scaling, offset tracking, and '
         'consumer backpressure.\n'
         '2. If Pub/Sub must be used, decouple listening from processing using an in-memory queue (`asyncio.Queue` or '
         'Python worker pool) so the network socket is read at line speed without blocking on compute.')],
 '14': [('TombstoneOverwhelmingException on Wide-Row Scan',
         'CREATE TABLE user_notifications (\n'
         '    user_id uuid,\n'
         '    notification_id timeuuid,\n'
         '    is_read boolean,\n'
         '    payload text,\n'
         '    PRIMARY KEY (user_id, notification_id)\n'
         ') WITH CLUSTERING ORDER BY (notification_id DESC);\n'
         '\n'
         '-- Application cleanup query run every hour:\n'
         'DELETE FROM user_notifications \n'
         'WHERE user_id = ? AND notification_id < ?;\n'
         '\n'
         '-- Read query executed when user opens inbox:\n'
         'SELECT * FROM user_notifications \n'
         'WHERE user_id = ? AND is_read = false \n'
         'LIMIT 20;\n',
         'Read query fails with: org.apache.cassandra.exceptions.ReadFailureException: Server failure during read '
         'query at consistency LOCAL_QUORUM (Scanned over 100001 tombstones in user_notifications; query aborted).',
         ['What is a tombstone in Cassandra, and why did deleting old notifications break subsequent read queries?',
          'How can you view tombstone counts per SSTable using `nodetool` and sstable tools?',
          'What table design and operational adjustments eliminate tombstone scanning overhead?'],
         '**Root Cause:**\n'
         'In Cassandra (and LSM architectures), `DELETE` does not immediately remove data from disk. Instead, it '
         'writes a deletion marker called a **tombstone** with a timestamp. When reading data, Cassandra must scan all '
         'clustering rows—including tombstones—to determine whether data was deleted. By default, if a single query '
         'scans more than 100,000 tombstones (`tombstone_failure_threshold`), Cassandra aborts the query to prevent '
         'JVM heap exhaustion and Garbage Collection pauses.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check tombstone warnings in `system.log`:\n'
         '   ```bash\n'
         '   grep -i "tombstone" /var/log/cassandra/system.log\n'
         '   ```\n'
         '2. Inspect SSTable metadata using `sstablemetadata`:\n'
         '   ```bash\n'
         '   sstablemetadata /var/lib/cassandra/data/keyspace/user_notifications-*/nb-1-big-Data.db | grep -i '
         '"tombstone"\n'
         '   ```\n'
         '3. Check table statistics:\n'
         '   ```bash\n'
         '   nodetool tablestats keyspace.user_notifications\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **TTL Instead of DELETE:** Use native column/row TTL (`INSERT ... USING TTL 2592000`) and Time-Window '
         'Compaction Strategy (TWCS), which drops entire expired SSTables without generating tombstones.\n'
         '2. **Bucket the Partition:** Partition by user and month/week (`PRIMARY KEY ((user_id, year_month), '
         'notification_id)`). To clear old data, drop old partition buckets rather than issuing cell-level `DELETE`.\n'
         '3. **Tune GC Grace Seconds:** For tables where deleted data does not need resurrection protection for 10 '
         'days, lower `gc_grace_seconds` from 864,000 (10 days) to e.g. 86,400 (1 day) if repairs run frequently.'),
        ('Last-Write-Wins (LWW) Silent Data Loss via Clock Skew',
         '# Microservice A on Host 1 (Clock skewed: 2026-09-08 10:05:00 UTC)\n'
         'session.execute(\n'
         '    "UPDATE accounts SET status = \'ACTIVE\' WHERE account_id = %s",\n'
         '    (acc_id,)\n'
         ')\n'
         '\n'
         '# Microservice B on Host 2 (Accurate NTP: 2026-09-08 10:00:00 UTC)\n'
         '# Executed 2 minutes LATER in real time:\n'
         'session.execute(\n'
         '    "UPDATE accounts SET status = \'SUSPENDED\' WHERE account_id = %s",\n'
         '    (acc_id,)\n'
         ')\n',
         'Even though Microservice B executed the SUSPENDED update 2 minutes after Microservice A, querying the '
         "database returns status = 'ACTIVE'. The later update was discarded.",
         ["How does Cassandra's Last-Write-Wins (LWW) conflict resolution mechanism determine the winning mutation?",
          'How can you inspect the internal timestamp of a column cell in CQL?',
          'How do you guarantee monotonic write ordering or prevent clock skew anomalies in distributed systems?'],
         '**Root Cause:**\n'
         'Cassandra resolves concurrent writes to the same cell using **Last-Write-Wins (LWW)** based on '
         "microsecond-level timestamps generated either by the client driver or the coordinator node. Because Host 1's "
         'system clock was drifting 5 minutes into the future (+300s), its write carried timestamp $T + 300s$. When '
         'Host 2 issued its write at real time $T + 120s$, Cassandra compared timestamps: $(T + 300s) > (T + 120s)$, '
         "and silently ignored Host 2's mutation as an older update.\n"
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Query the writetime of the cell in CQL:\n'
         '   ```sql\n'
         '   SELECT status, WRITETIME(status) FROM accounts WHERE account_id = 12345;\n'
         '   ```\n'
         '2. Verify clock synchronization across cluster and application servers:\n'
         '   ```bash\n'
         '   chronyc tracking   # or ntpstat / timedatectl\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **NTP Monitoring:** Maintain sub-millisecond clock synchronization across all Cassandra nodes and client '
         'application hosts using `chrony` with strict alerting on clock jitter > 5ms.\n'
         '2. **Lightweight Transactions (LWT / Paxos):** When deterministic linearizable ordering is required, use '
         "Paxos conditional updates (`IF status = '...'`) which use ballot numbers rather than wall clocks:\n"
         '   ```sql\n'
         "   UPDATE accounts SET status = 'SUSPENDED' WHERE account_id = ? IF status = 'ACTIVE';\n"
         '   ```'),
        ('Wide-Row Latency Spike and Read Repair Storm',
         'CREATE TABLE device_telemetry (\n'
         '    device_type text,         -- e.g. "temperature_sensor"\n'
         '    recorded_at timestamp,\n'
         '    device_id text,\n'
         '    reading double,\n'
         '    PRIMARY KEY (device_type, recorded_at, device_id)\n'
         ');\n'
         '\n'
         "-- Inserted 500,000,000 records under device_type = 'temperature_sensor'\n"
         '-- Query:\n'
         'SELECT * FROM device_telemetry \n'
         "WHERE device_type = 'temperature_sensor' \n"
         'ORDER BY recorded_at DESC LIMIT 50;\n',
         'p99 read latency spikes to 8,000ms. Node JVM experiences consecutive 15-second Stop-The-World GC pauses. '
         'nodetool tpstats shows high ReadRepairStage and MutationStage backpressure.',
         ['Why is partitioning by `device_type` a catastrophic anti-pattern in Cassandra?',
          'What is the recommended maximum partition size in Cassandra, and how do you inspect partition sizes with '
          '`nodetool`?',
          'How should the primary key be re-modeled to distribute telemetry evenly across the token ring?'],
         '**Root Cause:**\n'
         'Cassandra stores each partition as a contiguous structure on disk and in memory. The entire partition for '
         "`device_type = 'temperature_sensor'` hashes to a single token in the ring, concentrating hundreds of "
         'gigabytes onto a single primary node and its replicas. When querying this partition, Cassandra must load '
         'large index offsets into JVM heap, triggering violent Stop-The-World garbage collection pauses and read '
         'timeouts.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Find large partitions:\n'
         '   ```bash\n'
         '   nodetool tablestats keyspace.device_telemetry | grep -i "compacted partition minimum bytes\\|maximum '
         'bytes"\n'
         '   ```\n'
         '2. Check GC pauses:\n'
         '   ```bash\n'
         '   nodetool gcstats\n'
         '   ```\n'
         '3. Check thread pool drops:\n'
         '   ```bash\n'
         '   nodetool tpstats | grep ReadStage\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Cassandra Partition Rule of Thumb:** Partition size must stay under **100MB** and fewer than 100,000 '
         'clustering cells.\n'
         '2. **Compound Partition Key:** Partition by `(device_id, date)` so data is evenly dispersed across the token '
         'ring and bounded per day:\n'
         '   ```sql\n'
         '   CREATE TABLE device_telemetry (\n'
         '       device_id text,\n'
         '       day date,\n'
         '       recorded_at timestamp,\n'
         '       reading double,\n'
         '       PRIMARY KEY ((device_id, day), recorded_at)\n'
         '   ) WITH CLUSTERING ORDER BY (recorded_at DESC);\n'
         '   ```'),
        ('Secondary Index Scatter-Gather Timeout with ALLOW FILTERING',
         'CREATE TABLE user_profiles (\n'
         '    user_id uuid PRIMARY KEY,\n'
         '    country_code text,\n'
         '    email text,\n'
         '    signup_date date\n'
         ');\n'
         '\n'
         'CREATE INDEX idx_users_country ON user_profiles(country_code);\n'
         '\n'
         '-- Query executed by analytics dashboard:\n'
         'SELECT * FROM user_profiles \n'
         "WHERE country_code = 'US' AND signup_date >= '2026-01-01' \n"
         'ALLOW FILTERING;\n',
         'Analytics query times out with NoHostAvailableException after 12 seconds. Cassandra nodes CPU spikes to 100% '
         'across all 12 nodes in the cluster simultaneously.',
         ['How do 2i (secondary indexes) execute in Cassandra, and why is `ALLOW FILTERING` dangerous on large '
          'clusters?',
          'What tool or tracing command reveals the scatter-gather coordinator execution plan?',
          'What query-driven data modeling pattern replaces secondary indexes for high-throughput filtering?'],
         '**Root Cause:**\n'
         'Cassandra secondary indexes are **local indexes**, not global. Every node indexes only the partitions stored '
         'locally on that specific node. When querying by `country_code`, the coordinator node has no idea which node '
         'holds matching data, so it must issue a **scatter-gather broadcast** to every single node in the cluster. '
         'Adding `ALLOW FILTERING` forces every node to sequentially read and discard non-matching rows in memory '
         'across millions of partitions, causing cluster-wide CPU starvation.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run tracing in cqlsh:\n'
         '   ```sql\n'
         '   TRACING ON;\n'
         "   SELECT * FROM user_profiles WHERE country_code = 'US' AND signup_date >= '2026-01-01' ALLOW FILTERING;\n"
         '   ```\n'
         '   Examine the trace: you will see `Executing single-partition query` executed thousands of times on all '
         'nodes.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Materialized Table / Query-First Modeling:** Create a query-specific table keyed by the search '
         'criteria:\n'
         '   ```sql\n'
         '   CREATE TABLE users_by_country_date (\n'
         '       country_code text,\n'
         '       signup_date date,\n'
         '       user_id uuid,\n'
         '       email text,\n'
         '       PRIMARY KEY ((country_code, signup_date), user_id)\n'
         '   );\n'
         '   ```\n'
         '2. Or use SASI (SSTable-Attached Secondary Indexes) for prefix search, or replicate data to '
         'Elasticsearch/OpenSearch for ad-hoc analytical queries.'),
        ('Gossip Lag and WriteTimeoutException on Hint Hand-off Saturation',
         '# 3-Node Cassandra Cluster (Node 1, Node 2, Node 3)\n'
         '# Replication factor: 3. Consistency Level: LOCAL_QUORUM (needs 2 acks)\n'
         '\n'
         '# Node 2 undergoes a 4-hour hardware maintenance outage.\n'
         '# Node 1 and Node 3 handle all writes and buffer mutations into Hints.\n'
         '# Node 2 boots back up.\n',
         'As soon as Node 2 boots up, writes across the cluster begin failing with WriteTimeoutException: Operation '
         'timed out - received only 1 responses. Node 1 and 3 disk I/O climbs to 100% utilization.',
         ["What are Hints in Cassandra, and why did Node 2's recovery overwhelm the remaining nodes?",
          'How do you monitor hinted handoff delivery and throttle hint dispatching?',
          'What is `max_hint_window_in_ms`, and what should be done if a node is offline longer than the window?'],
         '**Root Cause:**\n'
         'When a replica is unreachable, coordinators store write mutations locally as **hints** for up to '
         '`max_hint_window_in_ms` (default 3 hours). If Node 2 was down for 4 hours, hints stopped accumulating after '
         'hour 3. When Node 2 came back, Node 1 and 3 immediately began streaming gigabytes of stored hints while '
         'simultaneously handling ongoing user writes and read repairs. The unthrottled hint replay saturated network '
         'and disk I/O, causing coordinators to drop client write acknowledgments within the 2,000ms write timeout.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check pending hints:\n'
         '   ```bash\n'
         '   nodetool getendpoints keyspace table key\n'
         '   nodetool tpstats | grep -i hint\n'
         '   ```\n'
         '2. Check gossip status:\n'
         '   ```bash\n'
         '   nodetool gossipinfo\n'
         '   nodetool status\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Throttle Hint Delivery:** In `cassandra.yaml`:\n'
         '   ```yaml\n'
         '   hinted_handoff_throttle_in_kb: 10240   # Throttle hint replay to 10MB/s\n'
         '   max_hints_delivery_threads: 2\n'
         '   ```\n'
         '2. **If node is down longer than 3 hours:** Do not rely on hints. Node 2 has missed mutations that were '
         'dropped after the 3-hour window. Immediately run a full repair on Node 2 upon recovery:\n'
         '   ```bash\n'
         '   nodetool repair -pr keyspace  # Partition-range repair\n'
         '   ```')],
 '15': [('LSM Write Stall on Level-0 SSTable Pileup',
         '# RocksDB / LevelDB Storage Engine Configuration\n'
         'options.write_buffer_size = 64 * 1024 * 1024       # 64MB MemTable\n'
         'options.level0_file_num_compaction_trigger = 4\n'
         'options.level0_slowdown_writes_trigger = 8\n'
         'options.level0_stop_writes_trigger = 12\n'
         '\n'
         '# Ingestion script writing 50,000 rows/sec using Put()\n',
         'Write ingestion throughput suddenly collapses from 50,000 ops/sec to 0 for 4-8 seconds at a time. Storage '
         "logs show: 'Stalling writes because we have 12 L0 files; compaction is lagging behind'.",
         ['Why does Level 0 in an LSM-tree have key overlaps, and why does a backlog of L0 files force write stalls?',
          'What metrics in RocksDB/Cassandra expose pending compaction bytes and write stall durations?',
          'How can compaction concurrency and MemTable flushing be tuned to eliminate write stalls?'],
         '**Root Cause:**\n'
         'When a MemTable fills up, it is flushed to disk as an immutable SSTable in Level 0 (L0). Unlike Levels 1 '
         'through N (where keys are non-overlapping and sorted), L0 SSTables have overlapping key ranges because each '
         'file represents a snapshot of MemTable keys at a different point in time. Therefore, every point read must '
         'check *every* L0 SSTable. To prevent read amplification from spiraling out of control, the engine '
         'deliberately stalls or stops incoming writes (`level0_stop_writes_trigger`) when L0 compaction threads '
         'cannot keep up with flush speed.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check RocksDB statistics / LOG:\n'
         '   ```text\n'
         '   ** Compaction Stats [default] **\n'
         '   Level   Files   Size     Score\n'
         '   L0       12/4   768 MB   3.0   (Compaction pending)\n'
         '   ```\n'
         '2. In Cassandra:\n'
         '   ```bash\n'
         '   nodetool compactionstats\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. Increase compaction thread concurrency:\n'
         '   ```python\n'
         '   options.max_background_jobs = 8        # Allow parallel flushes and compactions\n'
         '   options.max_subcompactions = 4          # Parallelize single large SSTable compactions\n'
         '   ```\n'
         '2. Increase write buffer and trigger thresholds:\n'
         '   ```python\n'
         '   options.level0_file_num_compaction_trigger = 8\n'
         '   options.level0_slowdown_writes_trigger = 20\n'
         '   options.level0_stop_writes_trigger = 36\n'
         '   options.write_buffer_size = 128 * 1024 * 1024\n'
         '   ```\n'
         '3. Use dedicated fast NVMe SSD storage with high random I/O write capability.'),
        ('Bloom Filter False Positive Rate Causing Excessive Disk Seeks',
         '# LSM-tree custom implementation / configuration\n'
         '# Bloom filter initialized with 3 bits per key\n'
         'bloom_bits_per_key = 3   # Yields ~30% false positive probability\n'
         '\n'
         'def get(key: bytes):\n'
         '    if key in memtable:\n'
         '        return memtable[key]\n'
         '    for sstable in sstables:\n'
         '        if sstable.bloom_filter.contains(key):\n'
         '            # Disk seek and block read\n'
         '            val = sstable.read_block(key)\n'
         '            if val is not None:\n'
         '                return val\n'
         '    return None\n',
         'When looking up non-existent keys (cache-miss pattern), disk read IOPS spikes to 25,000 IOPS and p99 query '
         'latency jumps from 0.4ms to 35ms, even though 99% of queried keys do not exist in the database.',
         ['How does a Bloom filter accelerate point lookups in LSM SSTables, and how does `bits_per_key` impact false '
          'positive rate?',
          'What mathematical formula relates bits per key $m/n$ to false positive probability $p$?',
          'What is the industry standard bits-per-key allocation for LSM engines, and how much RAM is required?'],
         '**Root Cause:**\n'
         'A Bloom filter is a space-efficient probabilistic data structure that answers whether an element is '
         '*definitely not* in the set or *might be* in the set. If the filter returns false, the SSTable can be '
         'completely skipped without touching disk. With only 3 bits per key, the false positive probability is '
         'approximately $30\\%$. This means for every query of a non-existent key across 10 SSTables, the engine '
         'performs on average 3 unnecessary disk I/O seeks and block decodes.\n'
         '\n'
         '**Mathematical Proof:**\n'
         'The optimal false positive rate is:\n'
         '$$p \x07pprox \\left(\x0c'
         'rac{1}{2}\r'
         'ight)^{\\ln(2) \\cdot \x0c'
         'rac{m}{n}} \x07pprox 0.6185^{m/n}$$\n'
         '- At $m/n = 3$: $p \x07pprox 23.7\\%$\n'
         '- At $m/n = 10$: $p \x07pprox 0.8\\%$ to $1\\%$\n'
         '- At $m/n = 14$: $p \x07pprox 0.1\\%$\n'
         '\n'
         '**Production Fix:**\n'
         'Allocate **10 bits per key** (approx. 1.25 bytes per entry in RAM):\n'
         '```python\n'
         '# In RocksDB:\n'
         'options.table_factory = rocksdb.BlockBasedTableFactory(\n'
         '    filter_policy=rocksdb.NewBloomFilterPolicy(bits_per_key=10)\n'
         ')\n'
         '```\n'
         'For 100 million keys, 10 bits/key requires only $\x07pprox 120\text{ MB}$ of RAM and reduces disk reads for '
         'missing keys by 99%.'),
        ('DynamoDB Hot Partition Throttling via Hash Skew',
         'import boto3\n'
         "dynamodb = boto3.resource('dynamodb')\n"
         "table = dynamodb.Table('FlashSaleOrders')\n"
         '\n'
         "# Partition Key: status (String: 'PENDING', 'PROCESSED', 'SHIPPED')\n"
         '# Sort Key: order_id (String)\n'
         '\n'
         'def record_order(order_id: str, payload: dict):\n'
         '    table.put_item(\n'
         '        Item={\n'
         "            'status': 'PENDING',  # 99.8% of all incoming writes use 'PENDING'\n"
         "            'order_id': order_id,\n"
         '            **payload\n'
         '        }\n'
         '    )\n',
         'Client receives botocore.exceptions.ClientError: An error occurred (ProvisionedThroughputExceededException) '
         'when calling the PutItem operation. CloudWatch shows the table has 5,000 WCU provisioned, but total '
         'consumption is only 1,050 WCU.',
         ['Why is the table throttled even though total consumed capacity is well below the provisioned 5,000 WCU?',
          'What is the maximum throughput limit per individual physical partition in DynamoDB?',
          'How do you redesign the partition key with synthetic sharding / salt to distribute writes?'],
         '**Root Cause:**\n'
         'DynamoDB distributes tables across multiple internal storage partitions based on the MD5 hash of the '
         '**Partition Key**. An individual physical partition has a hard limit of **1,000 WCU** and **3,000 RCU**. '
         'When 5,000 WCU is provisioned, DynamoDB spreads that across at least 5 physical partitions. Because 99.8% of '
         "writes use `status = 'PENDING'`, all writes are routed to the single physical partition responsible for that "
         'key hash, capping write throughput at 1,000 WCU.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check CloudWatch metrics for `ProvisionedThroughputExceededEvents` vs `ConsumedWriteCapacityUnits`.\n'
         '2. Inspect CloudWatch Contributor Insights for DynamoDB to identify the exact hot partition keys.\n'
         '\n'
         '**Production Fix:**\n'
         'Use **Synthetic Partition Key Sharding (Write Salting)**:\n'
         '```python\n'
         'import random\n'
         '\n'
         'NUM_SHARDS = 10  # Distribute across 10 partitions -> up to 10,000 WCU\n'
         '\n'
         'def record_order(order_id: str, payload: dict):\n'
         '    shard_id = random.randint(0, NUM_SHARDS - 1)\n'
         '    table.put_item(\n'
         '        Item={\n'
         '            \'partition_key\': f"PENDING#{shard_id}",\n'
         "            'order_id': order_id,\n"
         '            **payload\n'
         '        }\n'
         '    )\n'
         '```\n'
         'Workers reading pending orders can query each shard in parallel (`PENDING#0` through `PENDING#9`).'),
        ('Size-Tiered Compaction Strategy (STCS) Disk Headroom Exhaustion',
         '-- Table configuration using Size-Tiered Compaction Strategy (STCS)\n'
         'CREATE TABLE user_activity_log (\n'
         '    user_id uuid,\n'
         '    activity_time timestamp,\n'
         '    action text,\n'
         '    PRIMARY KEY (user_id, activity_time)\n'
         ") WITH compaction = {'class': 'SizeTieredCompactionStrategy'};\n"
         '\n'
         '-- Disk size: 1.0 TB total. Current data volume: 680 GB (68% disk used).\n',
         'Compaction begins merging 4 large SSTables (160GB each). 2 hours into compaction, the node crashes with '
         'java.io.IOException: No space left on device. The node enters a crash loop and cannot boot.',
         ['Why does Size-Tiered Compaction require up to 50% free disk space headroom?',
          'How does Leveled Compaction Strategy (LCS) differ in terms of disk headroom requirements?',
          'How can an administrator recover a node with a full disk without corrupting SSTables?'],
         '**Root Cause:**\n'
         'In Size-Tiered Compaction (STCS), Cassandra merges 4 SSTables of similar size into 1 new, larger SSTable. '
         'During the compaction process, the original 4 SSTables must remain on disk to answer read queries until the '
         'new SSTable is fully written and fsynced. Therefore, merging four 160GB SSTables ($4 \times 160\text{ GB} = '
         '640\text{ GB}$) requires an additional 640GB of free space simultaneously. Since the node only had 320GB '
         'available, disk filled up completely.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check disk utilization:\n'
         '   ```bash\n'
         '   df -h /var/lib/cassandra/data\n'
         '   ```\n'
         '2. Check ongoing compactions:\n'
         '   ```bash\n'
         '   nodetool compactionstats\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Disk Headroom Rule for STCS:** Never allow disk utilization to exceed **50%** when using STCS.\n'
         '2. **Switch to Leveled Compaction Strategy (LCS):** LCS breaks data into small, fixed-size SSTables '
         '(typically 160MB). Compaction merges small files, requiring only **10%** disk headroom:\n'
         '   ```sql\n'
         "   ALTER TABLE user_activity_log WITH compaction = {'class': 'LeveledCompactionStrategy'};\n"
         '   ```\n'
         '3. **Emergency Recovery:**\n'
         '   - Temporarily mount an external disk and move older SSTable files.\n'
         '   - Run `nodetool stop COMPACTION` on boot if possible.\n'
         '   - Or run `sstable-scrub` after freeing space.'),
        ('DynamoDB Global Secondary Index (GSI) Write Throttling Backpressure',
         "# Main Table: 'Orders' (Provisioned: 4000 WCU, 4000 RCU)\n"
         "# Global Secondary Index: 'CustomerEmailIndex' (Provisioned: 200 WCU, 200 RCU)\n"
         '\n'
         'import boto3\n'
         "dynamodb = boto3.resource('dynamodb')\n"
         "table = dynamodb.Table('Orders')\n"
         '\n'
         '# Application inserting into main table\n'
         'table.put_item(\n'
         '    Item={\n'
         "        'order_id': 'ord_987123',\n"
         "        'customer_email': 'shopper@example.com',\n"
         "        'total': 120.50\n"
         '    }\n'
         ')\n',
         "PutItem writes to the main 'Orders' table fail with ProvisionedThroughputExceededException, even though main "
         'table write consumption is only 300 WCU against its 4,000 WCU limit.',
         ['Why does an undersized Global Secondary Index (GSI) cause write failures on the main table?',
          'What CloudWatch metric confirms GSI-induced backpressure?',
          'How should GSIs be provisioned, and when should DynamoDB on-demand capacity or sparse GSIs be used?'],
         '**Root Cause:**\n'
         'When an item is inserted or updated in a DynamoDB table, any Global Secondary Index that indexes an '
         "attribute present in the item must be updated asynchronously by DynamoDB's internal replication engine. If "
         'the GSI does not have enough Write Capacity Units (WCUs) to keep up with the write rate of the main table, '
         'DynamoDB throttles writes to the **main table** to prevent the GSI from falling indefinitely behind.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check CloudWatch metric:\n'
         '   `OnlineIndexPercentageProgress` and `IndexThrottleEvents` on `CustomerEmailIndex`.\n'
         '2. Compare `ConsumedWriteCapacityUnits` between base table and index.\n'
         '\n'
         '**Production Fix:**\n'
         "1. **Match Provisioning:** Ensure GSI WCU is provisioned to equal or exceed the base table's WCU (or enable "
         'Auto Scaling on both base table and GSIs).\n'
         '2. **Switch to On-Demand Billing:** If traffic is spiky, use `PAY_PER_REQUEST` billing so both the table and '
         'its GSIs scale automatically without provisioned limits.\n'
         '3. **Sparse Indexing:** Only include `customer_email` on items that actually need GSI indexing. If an item '
         'does not contain the GSI partition key, it will not be written to the GSI, saving GSI WCU.')],
 '16': [('Cartesian Product from Disconnected MATCH Clauses',
         '// Cypher query to find products bought by coworkers\n'
         'MATCH (u:User {id: $userId})\n'
         'MATCH (c:User)\n'
         'WHERE c.department = u.department AND c.id <> u.id\n'
         'MATCH (p:Product)\n'
         'WHERE (c)-[:BOUGHT]->(p)\n'
         'RETURN p.name, count(c) as coworkers_count\n',
         "Query takes 42 seconds for a graph with only 50,000 nodes. Neo4j logs show query warning: 'This query builds "
         "a Cartesian product between disconnected patterns'.",
         ['What is a Cartesian product in Cypher query planning, and where did it occur in this query?',
          'How can you view the query execution plan in Cypher using `EXPLAIN` and `PROFILE`?',
          'How should the query be rewritten to express relationship traversals directly without Cartesian joins?'],
         '**Root Cause:**\n'
         'In the query, `MATCH (p:Product)` is declared as an independent pattern disconnected from `(c:User)` before '
         "the WHERE clause is evaluated. Cypher's query planner executes a Cartesian product (`CartesianProduct` "
         'operator) combining every node in set `c` with every node in set `p` before filtering by the relationship. '
         'If there are 1,000 coworkers and 20,000 products, it evaluates $1,000 \times 20,000 = 20,000,000$ '
         'combinations in memory.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Prepend `EXPLAIN` or `PROFILE` in Neo4j Browser or `cypher-shell`:\n'
         '   ```cypher\n'
         '   PROFILE\n'
         '   MATCH (u:User {id: $userId})\n'
         '   MATCH (c:User)\n'
         '   WHERE c.department = u.department AND c.id <> u.id\n'
         '   MATCH (p:Product)\n'
         '   WHERE (c)-[:BOUGHT]->(p)\n'
         '   RETURN p.name, count(c);\n'
         '   ```\n'
         '2. Look for the red `CartesianProduct` operator in the execution tree.\n'
         '\n'
         '**Production Fix:**\n'
         'Express the relationship traversal directly in a single connected `MATCH` pattern:\n'
         '```cypher\n'
         'MATCH (u:User {id: $userId})\n'
         'MATCH (u)-[:WORKS_IN]->(d:Department)<-[:WORKS_IN]-(c:User)\n'
         'WHERE c.id <> u.id\n'
         'MATCH (c)-[:BOUGHT]->(p:Product)\n'
         'RETURN p.name, count(DISTINCT c) AS coworkers_count;\n'
         '```\n'
         'This uses pointer-hopping index-free adjacency instead of full-table scanning and Cartesian products.'),
        ('Unbounded Variable-Length Path Traversal OOM',
         '// Cypher query to check if two users are connected in a social network\n'
         "MATCH (a:User {email: 'alice@example.com'}), (b:User {email: 'bob@example.com'})\n"
         'MATCH path = (a)-[:FOLLOWS*]-(b)\n'
         'RETURN path\n'
         'LIMIT 1;\n',
         'Neo4j server JVM crashes with java.lang.OutOfMemoryError: Java heap space. All active database transactions '
         'are killed.',
         ['Why does `[:FOLLOWS*]` cause exponential path explosion even with `LIMIT 1`?',
          'How do you set transaction execution timeouts in `neo4j.conf`?',
          'How should shortest-path algorithms or bounded hops be used instead?'],
         '**Root Cause:**\n'
         '`[:FOLLOWS*]` specifies an unbounded variable-length path traversal across bidirectional edges. In a graph '
         'with cycles and high connectivity, the number of possible paths between two nodes grows exponentially '
         '$O(d^k)$ with degree $d$ and depth $k$. Even though `LIMIT 1` is present, the depth-first search or '
         'breadth-first search path matcher enumerates millions of cyclic paths into heap memory before locating a '
         'path that satisfies all criteria.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect query logs in `logs/query.log` to identify queries exceeding memory thresholds.\n'
         '2. Check memory allocations:\n'
         '   ```bash\n'
         '   neo4j-admin server status\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Always bound path length:**\n'
         '   ```cypher\n'
         '   MATCH path = (a)-[:FOLLOWS*1..4]-(b)\n'
         '   RETURN path LIMIT 1;\n'
         '   ```\n'
         '2. **Use shortestPath() algorithm:**\n'
         '   Neo4j has specialized bidirectional breadth-first search algorithms that prune paths immediately:\n'
         '   ```cypher\n'
         "   MATCH (a:User {email: 'alice@example.com'}), (b:User {email: 'bob@example.com'})\n"
         '   MATCH path = shortestPath((a)-[:FOLLOWS*..6]->(b))\n'
         '   RETURN path;\n'
         '   ```\n'
         '3. Guard in `neo4j.conf`:\n'
         '   ```properties\n'
         '   dbms.transaction.timeout=10s\n'
         '   dbms.memory.transaction.global_max_size=4G\n'
         '   ```'),
        ('Supernode Degree Explosion Latency',
         "// Node 'Brand_Nike' is connected to 2,500,000 followers\n"
         'MATCH (u:User {id: $userId})-[:FOLLOWS]->(celebrity:User)<-[:FOLLOWS]-(other:User)\n'
         'RETURN other.id, count(*) as common_connections\n'
         'ORDER BY common_connections DESC\n'
         'LIMIT 10;\n',
         'For regular users with 50 followers, query runs in 4ms. When executed for a user who follows a '
         'celebrity/supernode, query runs for 28,000ms with high CPU usage.',
         ["What is a 'supernode' in graph databases, and why does traversing through a supernode destroy query "
          'performance?',
          'How can you check the degree (number of relationships) of a node in Cypher before traversing it?',
          'What graph modeling patterns (such as relationship filtering, edge bucketing, or sampling) mitigate '
          'supernode bottlenecks?'],
         '**Root Cause:**\n'
         'A **supernode** (or dense node) is a node with an abnormally high degree (e.g., thousands or millions of '
         'relationships). Graph databases rely on **index-free adjacency**, following physical relationship pointers '
         'stored on the node record. When traversing through a supernode with 2.5 million relationships, the engine '
         'must iterate through 2.5 million relationship records in memory, defeating the performance benefits of graph '
         'traversals.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check the degree of high-density nodes:\n'
         '   ```cypher\n'
         '   MATCH (u:User {id: $celebrityId})\n'
         '   RETURN count { (u)<-[:FOLLOWS]-() } AS in_degree;\n'
         '   ```\n'
         '2. In `PROFILE`, observe hundreds of thousands of `Expand(All)` rows produced.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Filter by Degree during Traversal:** Do not expand through nodes whose degree exceeds a threshold:\n'
         '   ```cypher\n'
         '   MATCH (u:User {id: $userId})-[:FOLLOWS]->(celebrity:User)\n'
         '   WHERE count { (celebrity)<-[:FOLLOWS]-() } < 50000\n'
         '   MATCH (celebrity)<-[:FOLLOWS]-(other:User)\n'
         '   RETURN other.id, count(*)\n'
         '   LIMIT 10;\n'
         '   ```\n'
         '2. **Node Bucketing (Fan-Out Partitioning):** Split the celebrity node into sub-nodes (`Celebrity_Bucket_1`, '
         '`Celebrity_Bucket_2`) or maintain pre-aggregated counts and summary relationships instead of raw individual '
         'graph edges.'),
        ('Cypher Eager Operator Blocking Heap Streaming',
         'MATCH (u:User)\n'
         'WHERE u.active = true\n'
         'SET u.last_checked = datetime()\n'
         'WITH u\n'
         'MATCH (u)-[:OWNS]->(a:Asset)\n'
         'RETURN u.name, count(a)\n',
         'When executing this query on a database with 2 million users, query execution halts for 35 seconds and Neo4j '
         'throws java.lang.OutOfMemoryError: Java heap space. The query does not stream results.',
         ['What is an `Eager` operator in Cypher, and why did modifying `u.last_checked` introduce an Eager barrier?',
          'How do you detect the `Eager` operator in Cypher execution plans?',
          'How do you decouple write operations from reads using `CALL { ... } IN TRANSACTIONS` to stream data '
          'cleanly?'],
         '**Root Cause:**\n'
         'Cypher protects queries against phantom reads and self-mutation hazards (e.g., updating a node that might be '
         're-matched later in the same query). To prevent this, the planner inserts an **Eager** operator whenever a '
         'query alternates between writes (`SET`, `CREATE`, `DELETE`) and subsequent reads/matches. An Eager operator '
         'forces Cypher to buffer the entire intermediate result set into JVM heap memory before allowing the next '
         'pipeline step to execute, breaking streaming and exhausting heap space.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run `EXPLAIN` on the query:\n'
         '   ```cypher\n'
         '   EXPLAIN\n'
         '   MATCH (u:User) WHERE u.active = true\n'
         '   SET u.last_checked = datetime()\n'
         '   WITH u MATCH (u)-[:OWNS]->(a:Asset) RETURN u.name, count(a);\n'
         '   ```\n'
         '2. Inspect the plan for `Eager` or `EagerAggregation` steps.\n'
         '\n'
         '**Production Fix:**\n'
         '1. Separate reads from writes, or batch writes using subqueries with periodic transactions:\n'
         '   ```cypher\n'
         '   MATCH (u:User) WHERE u.active = true\n'
         '   CALL {\n'
         '       WITH u\n'
         '       SET u.last_checked = datetime()\n'
         '   } IN TRANSACTIONS OF 10000 ROWS;\n'
         '   ```\n'
         '2. Read all data first before issuing writes at the end of the query:\n'
         '   ```cypher\n'
         '   MATCH (u:User)-[:OWNS]->(a:Asset)\n'
         '   WHERE u.active = true\n'
         '   WITH u, count(a) AS asset_count\n'
         '   SET u.last_checked = datetime()\n'
         '   RETURN u.name, asset_count;\n'
         '   ```'),
        ('Duplicate Node Creation Under Concurrent MERGE Without Constraint',
         '# Concurrent Python worker processes\n'
         'def get_or_create_device(device_uuid: str):\n'
         '    with driver.session() as session:\n'
         '        session.run(\n'
         '            "MERGE (d:Device {uuid: $uuid}) "\n'
         '            "ON CREATE SET d.created_at = timestamp() "\n'
         '            "RETURN d",\n'
         '            uuid=device_uuid\n'
         '        )\n'
         '\n'
         "# 20 workers concurrently process telemetry for device 'dev-abc-123'\n",
         "After concurrent execution, querying MATCH (d:Device {uuid: 'dev-abc-123'}) returns 4 duplicate nodes with "
         'identical UUIDs.',
         ['Why does `MERGE` fail to prevent duplicates under concurrent execution without a uniqueness constraint?',
          'What internal lock mechanism does Neo4j use when a uniqueness constraint is present vs absent?',
          'What Cypher DDL statement guarantees idempotent node creation under concurrency?'],
         '**Root Cause:**\n'
         '`MERGE` in Cypher is semantically equivalent to: "MATCH the node; if not found, CREATE it". Without a unique '
         'constraint or unique index on `:Device(uuid)`, concurrent transactions executing the initial `MATCH` phase '
         'will both see that the node does not exist. Both transactions proceed to the `CREATE` step and commit '
         'independent nodes. Neo4j only acquires schema locks to enforce uniqueness when a **UNIQUE CONSTRAINT** is '
         'defined.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check existing constraints:\n'
         '   ```cypher\n'
         '   SHOW CONSTRAINTS;\n'
         '   ```\n'
         '2. Check for duplicates in database:\n'
         '   ```cypher\n'
         '   MATCH (d:Device)\n'
         '   WITH d.uuid AS uuid, count(d) AS cnt, collect(d) AS nodes\n'
         '   WHERE cnt > 1\n'
         '   RETURN uuid, cnt;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         'Create a unique property constraint on the label and property before running concurrent `MERGE` operations:\n'
         '```cypher\n'
         'CREATE CONSTRAINT constraint_device_uuid FOR (d:Device) REQUIRE d.uuid IS UNIQUE;\n'
         '```\n'
         'With this constraint active, Neo4j takes an exclusive lock during the `MERGE` operation. Any concurrent '
         'transaction attempting to `MERGE` the same `uuid` will wait on the lock and match the newly committed node '
         'instead of creating a duplicate.')],
 '17': [("ClickHouse 'Too Many Parts in All Data Parts in Table'",
         '# Microservice publishing real-time events to ClickHouse\n'
         'from clickhouse_driver import Client\n'
         "client = Client('clickhouse.internal')\n"
         '\n'
         'def on_user_event(event: dict):\n'
         '    # Inserts single row immediately upon event receipt (1,000 events/sec)\n'
         '    client.execute(\n'
         '        "INSERT INTO user_events (user_id, event_type, created_at) VALUES",\n'
         "        [(event['user_id'], event['type'], event['time'])]\n"
         '    )\n',
         'After 15 minutes of operation, ClickHouse rejects all inserts with: DB::Exception: Too many parts in all '
         "data parts in table 'user_events' (305 parts, maximum allowed 300). Merges are processing slower than parts "
         'are being created.',
         ["How does ClickHouse's MergeTree engine persist inserted data, and why are single-row inserts fatal?",
          'Which system table allows inspecting part counts and active background merges in ClickHouse?',
          'What architectural patterns (buffer tables, application batching, or Kafka engine) solve this problem?'],
         '**Root Cause:**\n'
         'Every `INSERT` into a ClickHouse `MergeTree` table creates a new immutable on-disk **part** containing '
         'columnar compressed files for each column. ClickHouse runs background merge threads to asynchronously '
         'combine small parts into larger parts. ClickHouse is designed for inserts of $10,000$ to $100,000$ rows per '
         'batch. Inserting 1 row at a time 1,000 times per second creates 1,000 parts per second. The background merge '
         'process is quickly overwhelmed, and ClickHouse enforces the `parts_to_throw_insert` safety limit (default '
         '300) to protect the filesystem.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect part count in `system.parts`:\n'
         '   ```sql\n'
         '   SELECT table, count() as total_parts, sum(rows) as total_rows\n'
         '   FROM system.parts\n'
         "   WHERE active = 1 AND table = 'user_events'\n"
         '   GROUP BY table;\n'
         '   ```\n'
         '2. Check background merge activity:\n'
         '   ```sql\n'
         '   SELECT * FROM system.merges;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Application-Level Micro-Batching:** Accumulate records in memory (e.g. using `queue.Queue` or vector '
         'buffers) and flush in batches of at least 5,000 rows or every 2 seconds.\n'
         '2. **ClickHouse Buffer Table:** Insert into an in-memory `Buffer` table engine that flushes to `MergeTree` '
         'in batches:\n'
         '   ```sql\n'
         '   CREATE TABLE user_events_buffer AS user_events ENGINE = Buffer(\n'
         '       currentDatabase(), user_events, 16, 5, 10, 10000, 100000, 10000000, 100000000\n'
         '   );\n'
         '   ```\n'
         "3. **Kafka Table Engine:** Ingest from Kafka topics using ClickHouse's native `ENGINE = Kafka` which batches "
         'messages automatically.'),
        ('Run-Length Encoding (RLE) Negative Compression on High-Cardinality Column',
         '-- Parquet / ClickHouse Columnar Table definition\n'
         'CREATE TABLE sensor_readings (\n'
         '    metric_id UUID,                -- High cardinality: 10,000,000 distinct UUIDs\n'
         '    device_status LowCardinality(String),\n'
         '    reading Float64,\n'
         '    timestamp DateTime\n'
         ') ENGINE = MergeTree()\n'
         'ORDER BY (timestamp, metric_id);\n'
         '\n'
         '-- Code uses RLE / Dictionary compression on metric_id\n',
         'Parquet / ClickHouse table storage size for metric_id is 30% LARGER than raw uncompressed binary data. '
         'Column scans over metric_id are 4x slower than scanning uncompressed data.',
         ['How does Run-Length Encoding (RLE) and Dictionary encoding work, and why does it fail on high-cardinality '
          'sorted data?',
          'How can you inspect column compression ratios and physical sizes in ClickHouse or Parquet files?',
          'What encoding algorithm is optimal for UUIDs, timestamps, and high-cardinality float measurements?'],
         '**Root Cause:**\n'
         'Run-Length Encoding (RLE) compresses contiguous repeating values by storing `(value, count)` pairs. '
         'Dictionary encoding replaces values with integer pointers into a symbol dictionary. For high-cardinality '
         'columns (like unique UUIDs or random measurements) where values never repeat consecutively, RLE replaces a '
         '16-byte UUID with a `(16-byte UUID, count=1)` pair (e.g. 20 bytes), resulting in negative compression. '
         'Dictionary encoding builds a dictionary that contains every single key, adding massive index overhead.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check column compression in ClickHouse:\n'
         '   ```sql\n'
         '   SELECT column, type, data_compressed_bytes, data_uncompressed_bytes,\n'
         '          round(data_uncompressed_bytes / data_compressed_bytes, 2) AS ratio,\n'
         '          compression_codec\n'
         '   FROM system.columns\n'
         "   WHERE table = 'sensor_readings';\n"
         '   ```\n'
         '2. Inspect Parquet metadata with `parquet-tools meta file.parquet`.\n'
         '\n'
         '**Production Fix:**\n'
         '1. Do not use `LowCardinality` or dictionary encoding on UUIDs or high-cardinality identifiers.\n'
         '2. Configure specialized codecs based on data type:\n'
         '   - **UUID / Hashes:** Generic LZ4 or ZSTD: `CODEC(ZSTD(3))`\n'
         '   - **Timestamps / Incremental IDs:** DoubleDelta with ZSTD: `CODEC(DoubleDelta, ZSTD)`\n'
         '   - **Floating Point Readings:** Gorilla or FPC (Floating Point Compression): `CODEC(Gorilla, ZSTD)`\n'
         '   - **Low-cardinality strings (<10,000 distinct):** `LowCardinality(String)` (uses dictionary + RLE)'),
        ('DuckDB Out-Of-Memory Crash on Large Hash Join',
         'import duckdb\n'
         '\n'
         'con = duckdb.connect()\n'
         '# Memory limit set for container\n'
         'con.execute("SET max_memory = \'4GB\'")\n'
         '# Temp directory set to disabled / read-only path\n'
         '\n'
         '# Query joining two 20GB Parquet datasets\n'
         'con.execute("""\n'
         '    SELECT a.customer_id, count(b.transaction_id), sum(b.amount)\n'
         "    FROM 'customers_large.parquet' a\n"
         "    JOIN 'transactions_large.parquet' b ON a.customer_id = b.customer_id\n"
         '    GROUP BY a.customer_id\n'
         '""").fetchall()\n',
         'Query terminates with duckdb.duckdb.OutOfMemoryException: Out of Memory Error: could not allocate block of '
         'size 268435456 bytes (4GB max_memory reached). Process crashes without finishing aggregation.',
         ['Why does a hash join require significant memory, and how does DuckDB manage out-of-core (disk spilling) '
          'execution?',
          'What configuration setting in DuckDB enables external spilling to disk for memory-constrained queries?',
          'How can the query be optimized using Parquet projection pushdown and partition pruning?'],
         '**Root Cause:**\n'
         'In a standard hash join, DuckDB builds an in-memory hash table of the build-side relation (e.g. '
         "`customers_large`). When both relations exceed available RAM (`max_memory = '4GB'`), DuckDB requires an "
         'active temporary directory to spill intermediate hash partitions and sort buffers to disk (external / '
         'out-of-core processing). If temp disk spilling is not configured or disk permissions fail, DuckDB throws '
         '`OutOfMemoryException` once memory allocation reaches `max_memory`.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check memory and temp settings in DuckDB:\n'
         '   ```sql\n'
         "   SELECT * FROM duckdb_settings() WHERE name IN ('max_memory', 'temp_directory', "
         "'preserve_insertion_order');\n"
         '   ```\n'
         '2. Enable profiling to check memory allocation:\n'
         '   ```sql\n'
         '   PRAGMA enable_profiling;\n'
         "   PRAGMA profiling_output = 'profile.json';\n"
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Enable Disk Spilling:** Specify a writable directory for temporary data spilling:\n'
         '   ```python\n'
         '   con.execute("PRAGMA temp_directory = \'/tmp/duckdb_temp\'")\n'
         '   ```\n'
         '2. **Disable Insertion Order Preservation:** Setting `preserve_insertion_order = false` significantly '
         'reduces memory overhead during large aggregations.\n'
         '3. **Projection Pushdown:** Select only the columns required for the join and aggregation, rather than '
         'scanning full schemas:\n'
         '   ```sql\n'
         '   SELECT a.customer_id, count(b.transaction_id), sum(b.amount)\n'
         "   FROM (SELECT customer_id FROM 'customers_large.parquet') a\n"
         "   JOIN (SELECT customer_id, transaction_id, amount FROM 'transactions_large.parquet') b\n"
         '     ON a.customer_id = b.customer_id\n'
         '   GROUP BY a.customer_id;\n'
         '   ```'),
        ('ClickHouse ReplacingMergeTree Unmerged Duplicate Rows',
         'CREATE TABLE user_subscriptions (\n'
         '    user_id UInt64,\n'
         '    plan_name String,\n'
         '    status String,\n'
         '    updated_at DateTime\n'
         ') ENGINE = ReplacingMergeTree(updated_at)\n'
         'ORDER BY (user_id);\n'
         '\n'
         "-- User upgrades from 'FREE' to 'PRO':\n"
         "INSERT INTO user_subscriptions VALUES (101, 'FREE', 'ACTIVE', '2026-01-01 10:00:00');\n"
         "INSERT INTO user_subscriptions VALUES (101, 'PRO', 'ACTIVE', '2026-02-01 10:00:00');\n"
         '\n'
         '-- User views current plan:\n'
         'SELECT * FROM user_subscriptions WHERE user_id = 101;\n',
         'Query returns 2 rows instead of 1: user 101 shows both FREE and PRO plans simultaneously.',
         ['When does `ReplacingMergeTree` actually deduplicate rows, and why did a direct `SELECT` return duplicates?',
          'What are the performance implications of adding `FINAL` to queries on large tables?',
          'How can deduplication be achieved efficiently without the performance penalty of `FINAL`?'],
         '**Root Cause:**\n'
         '`ReplacingMergeTree` does **not** deduplicate data on insert. Deduplication occurs solely in the background '
         'during asynchronous part merges at indeterminate times. A standard `SELECT` reads all active parts as-is, '
         'which will contain duplicates until background merges happen to coincide. Relying on `ReplacingMergeTree` '
         'for real-time unique lookups without explicit deduplication logic is an architectural flaw.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Force an on-demand merge to verify behavior:\n'
         '   ```sql\n'
         '   OPTIMIZE TABLE user_subscriptions FINAL;\n'
         '   SELECT * FROM user_subscriptions WHERE user_id = 101; -- Now returns 1 row\n'
         '   ```\n'
         '   *(Note: OPTIMIZE TABLE FINAL is an expensive administrative command and should never run in application '
         'request paths).*\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Use `FINAL` for low-volume reads:**\n'
         '   ```sql\n'
         '   SELECT * FROM user_subscriptions FINAL WHERE user_id = 101;\n'
         '   ```\n'
         '   *Caution:* In older ClickHouse versions, `FINAL` forces single-threaded merge processing across all '
         'parts.\n'
         '2. **Use `argMax()` Aggregation (Optimal OLAP pattern):**\n'
         '   ```sql\n'
         '   SELECT user_id, argMax(plan_name, updated_at) AS plan_name,\n'
         '          argMax(status, updated_at) AS status, max(updated_at) AS updated_at\n'
         '   FROM user_subscriptions\n'
         '   WHERE user_id = 101\n'
         '   GROUP BY user_id;\n'
         '   ```\n'
         '   This is parallel, highly vectorized, and guarantees accurate state without full-table `FINAL` locks.'),
        ('Vectorized Execution De-Optimization via Python UDF Row Fallback',
         'import duckdb\n'
         '\n'
         'con = duckdb.connect()\n'
         '\n'
         '# Custom row-by-row Python function\n'
         'def clean_phone(val: str) -> str:\n'
         '    if val is None:\n'
         '        return ""\n'
         '    import re\n'
         "    return re.sub(r'\\D', '', val)\n"
         '\n'
         'con.create_function("clean_phone", clean_phone, ["VARCHAR"], "VARCHAR")\n'
         '\n'
         '# Run on 50,000,000 customer records\n'
         'con.execute("""\n'
         "    SELECT clean_phone(phone_number) FROM 'customers.parquet'\n"
         '""").fetchall()\n',
         'Query latency jumps from 0.3 seconds to 118 seconds. CPU profiler shows 95% of execution time spent in '
         'Python C-API PyObject_Call and garbage collector overhead rather than columnar SIMD processing.',
         ['What is vectorized execution, and why does invoking a standard scalar Python function break vectorized '
          'pipelining?',
          'What is the per-row overhead of converting Arrow/columnar chunk buffers into individual Python objects?',
          'How can vector-native Arrow/PyArrow expressions or built-in DuckDB regex functions replace Python UDFs?'],
         '**Root Cause:**\n'
         'DuckDB is a vectorized OLAP database that processes data in columnar vectors of 2,048 values using CPU '
         'cache-friendly loops and SIMD vectorization instructions. When a scalar Python UDF is called row-by-row, the '
         'execution engine must break the vectorized vector, box each value into an individual `PyObject`, invoke the '
         'Python interpreter (acquiring the GIL), execute interpreted bytecode, unbox the return value, and repack it '
         'into an Arrow vector. Repeating this 50,000,000 times introduces massive context switching and memory '
         'allocation overhead.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Profile execution plan:\n'
         '   ```sql\n'
         "   EXPLAIN ANALYZE SELECT clean_phone(phone_number) FROM 'customers.parquet';\n"
         '   ```\n'
         '2. Look for `EXPRESSION` node with excessive execution time and scalar UDF barriers.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Use DuckDB Built-in SQL Functions:** DuckDB has native C++ SIMD-optimized regular expressions:\n'
         '   ```sql\n'
         "   SELECT regexp_replace(phone_number, '[^0-9]', '', 'g') FROM 'customers.parquet';\n"
         '   ```\n'
         '   This executes in < 0.5 seconds for 50 million records.\n'
         '2. **Use Vectorized PyArrow UDFs:** If a custom Python function is mandatory, define it as a vectorized '
         "Arrow compute function using `type='arrow'` so DuckDB passes PyArrow chunk arrays (thousands of rows at "
         'once) directly without row-by-row unboxing.')],
 '18': [('Lucene TooManyClauses Boolean Query Expansion Exception',
         'POST /products/_search\n'
         '{\n'
         '  "query": {\n'
         '    "wildcard": {\n'
         '      "sku_code": {\n'
         '        "value": "*AB*"\n'
         '      }\n'
         '    }\n'
         '  }\n'
         '}\n',
         'Elasticsearch returns HTTP 500: SearchPhaseExecutionException: all shards failed; nested: '
         'TooManyClauses[maxClauseCount is set to 1024]; nested: BooleanQuery$TooManyClauses.',
         ["Why does a leading wildcard query (`*AB*`) trigger Lucene's `TooManyClauses` exception?",
          "How does Lucene's inverted index structure make leading wildcard queries inefficient?",
          'What indexing strategies (`wildcard` field type, n-grams, or reverse token filters) solve substring '
          'searches efficiently?'],
         '**Root Cause:**\n'
         "Lucene's inverted index stores terms sorted lexicographically (e.g. `aa`, `ab`, `ac`). Prefix queries "
         '(`AB*`) perform a fast binary search to find the start term and scan until the prefix changes. However, a '
         'leading wildcard query (`*AB*`) cannot use binary search; it must iterate through *every term in the entire '
         'inverted index* dictionary for that field. Lucene rewrites this into a giant `BooleanQuery` consisting of an '
         '`OR` of every matching term. If matching terms exceed `indices.query.bool.max_clause_count` (default 1,024), '
         'Lucene aborts the query.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check Lucene terms on the shard:\n'
         '   ```bash\n'
         '   GET /products/_validate/query?explain=true\n'
         '   { "query": { "wildcard": { "sku_code": "*AB*" } } }\n'
         '   ```\n'
         '2. Observe `rewrite` method and clause counts.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Use `wildcard` field type (Elasticsearch 7.9+):**\n'
         '   ```json\n'
         '   PUT /products\n'
         '   {\n'
         '     "mappings": {\n'
         '       "properties": {\n'
         '         "sku_code": { "type": "wildcard" }\n'
         '       }\n'
         '     }\n'
         '   }\n'
         '   ```\n'
         '   The `wildcard` field type indexes n-grams and character n-gram automata internally, allowing arbitrary '
         'wildcard searches without BooleanQuery expansion.\n'
         '2. **N-Gram Tokenizer:** Index the field with an `ngram` or `edge_ngram` tokenizer so substrings are indexed '
         'as distinct tokens at ingest time.'),
        ("Deep Pagination OOM via 'from' + 'size' > 10,000",
         '# E-commerce export service\n'
         'page_number = 1500\n'
         'page_size = 50\n'
         '\n'
         'response = es.search(\n'
         '    index="orders",\n'
         '    body={\n'
         '        "from": page_number * page_size,  # from = 75,000\n'
         '        "size": page_size,                 # size = 50\n'
         '        "sort": [{"order_date": "desc"}]\n'
         '    }\n'
         ')\n',
         'Elasticsearch rejects request with: Result window is too large, from + size must be less than or equal to: '
         '[10000] but was [75050]. See the scroll api or search_after for more information.',
         ['Why does paginating with `from + size` across distributed shards scale with $O(N \\times \\text{shards})$ '
          'memory and CPU overhead?',
          'What setting controls the maximum result window, and why is increasing it a trap?',
          'How does `search_after` with Point-in-Time (PIT) solve deep pagination efficiently?'],
         '**Root Cause:**\n'
         'In a distributed index with $S$ primary shards, when a client requests `from: 75000, size: 50`, every shard '
         'must compute its local top $75,050$ matching documents and serialize their sort values back to the '
         'coordinating node. The coordinating node must deserialize and sort $S \times 75,050$ records in memory (e.g. '
         'across 5 shards = 375,250 records) before discarding 375,200 and returning the final 50. For deep pages, '
         'this causes severe heap memory pressure and coordinator crashes. Elasticsearch caps '
         '`index.max_result_window` at 10,000.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check current index settings:\n'
         '   ```bash\n'
         '   GET /orders/_settings?filter_path=*.settings.index.max_result_window\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         'Use **Point In Time (PIT)** and **`search_after`**:\n'
         '```python\n'
         '# 1. Open Point in Time\n'
         'pit = es.open_point_in_time(index="orders", keep_alive="2m")\n'
         'pit_id = pit["id"]\n'
         '\n'
         '# 2. Paginate using sort cursor\n'
         'response = es.search(body={\n'
         '    "size": 50,\n'
         '    "query": {"match_all": {}},\n'
         '    "pit": {"id": pit_id, "keep_alive": "2m"},\n'
         '    "sort": [{"order_date": "desc"}, {"_shard_doc": "asc"}],\n'
         '    "search_after": last_sort_values  # Cursor from previous page\n'
         '})\n'
         '\n'
         '# 3. Close PIT when done\n'
         'es.close_point_in_time(body={"id": pit_id})\n'
         '```\n'
         '`search_after` has $O(\text{size})$ complexity per page and constant memory overhead.'),
        ('Mapping Explosion from Dynamic JSON Keys',
         '# Ingesting raw webhook JSON payloads directly\n'
         'def ingest_webhook(payload: dict):\n'
         '    # Payload contains dynamic UUID keys:\n'
         '    # {"user_attributes": {"550e8400-e29b-41d4-a716-446655440000": "active", ...}}\n'
         '    es.index(\n'
         '        index="webhook_events",\n'
         '        document=payload\n'
         '    )\n',
         "Elasticsearch cluster state turns RED. Master node logs: 'Limit of total fields [1000] in index "
         "[webhook_events] has been exceeded'. Master CPU reaches 100% propagating cluster state updates.",
         ["What is a 'mapping explosion' in Elasticsearch, and why are dynamic JSON keys hazardous?",
          'What cluster-wide metadata must the master node synchronize on every new mapping field addition?',
          'How should dynamic key-value pairs be modeled using the `nested` or `flattened` data types?'],
         '**Root Cause:**\n'
         'By default, Elasticsearch uses **dynamic mapping**: whenever a new JSON key appears in an indexed document, '
         'Elasticsearch adds that field to the index mapping schema. Each field mapping is stored in the cluster state '
         'metadata. When documents contain unique keys (such as UUIDs, email addresses, or user IDs as keys), '
         'thousands of new fields are created daily. The cluster state balloons to hundreds of megabytes. Every '
         'mapping update must be serialized and acknowledged across every node in the cluster by the master node, '
         'causing master timeouts and cluster lockups.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect field count:\n'
         '   ```bash\n'
         '   GET /webhook_events/_mapping\n'
         '   ```\n'
         '2. Check cluster state size:\n'
         '   ```bash\n'
         '   GET /_cluster/state/metadata?filter_path=metadata.indices.webhook_events.mappings\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Use the `flattened` Field Type:** The `flattened` type indexes entire JSON objects as a single Lucene '
         'field without creating individual column mappings for each leaf key:\n'
         '   ```json\n'
         '   PUT /webhook_events\n'
         '   {\n'
         '     "mappings": {\n'
         '       "properties": {\n'
         '         "user_attributes": { "type": "flattened" }\n'
         '       }\n'
         '     }\n'
         '   }\n'
         '   ```\n'
         '2. **Key-Value Nested Array Pattern:** Restructure the data model:\n'
         '   ```json\n'
         '   "user_attributes": [\n'
         '       {"key": "uuid_123", "value": "active"}\n'
         '   ]\n'
         '   ```\n'
         '3. Disable dynamic mapping (`"dynamic": "strict"` or `"dynamic": "runtime"`).'),
        ('Stopword and Stemming Collisions on Exact Part Number Searches',
         'PUT /catalog\n'
         '{\n'
         '  "settings": {\n'
         '    "analysis": {\n'
         '      "analyzer": {\n'
         '        "standard_english": {\n'
         '          "type": "standard",\n'
         '          "stopwords": "_english_"\n'
         '        }\n'
         '      }\n'
         '    }\n'
         '  },\n'
         '  "mappings": {\n'
         '    "properties": {\n'
         '      "model_number": { "type": "text", "analyzer": "standard_english" }\n'
         '    }\n'
         '  }\n'
         '}\n'
         '\n'
         '-- Documents indexed: "Model IT-100", "Part A-OR-B", "Unit IN-55"\n'
         '-- Search for "IT-100":\n'
         'GET /catalog/_search\n'
         '{\n'
         '  "query": { "match": { "model_number": "IT-100" } }\n'
         '}\n',
         "Searching for 'IT-100' matches hundreds of irrelevant items containing '100', '200', '300', but fails to "
         "boost the exact 'IT-100' model. Searching for 'IN-55' returns 0 results.",
         ["Why did the search for 'IN-55' fail and 'IT-100' lose precision under the English analyzer?",
          'Which Elasticsearch API allows testing how a string is tokenized and filtered by an analyzer?',
          'How should part numbers and technical identifiers be modeled using multi-fields (`keyword` + custom '
          'tokenizers)?'],
         '**Root Cause:**\n'
         'The standard English analyzer applies tokenization and stopword removal:\n'
         '1. `IT` and `IN` are recognized as English stop words (`it`, `in`) and are completely dropped by the '
         'stopword filter.\n'
         '2. The standard tokenizer splits on punctuation, tokenizing `IT-100` into `[it, 100]`. Since `it` is '
         'removed, only `100` is indexed.\n'
         '3. Searching for `IT-100` removes `IT` from the query tokens as well, reducing the query to a search for the '
         "token `100`, matching every item with `100`. Searching for `IN-55` where `55` doesn't match returns "
         'nothing.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         'Use the `_analyze` API to test tokenization:\n'
         '```json\n'
         'POST /_analyze\n'
         '{\n'
         '  "analyzer": "standard_english",\n'
         '  "text": "Unit IN-55"\n'
         '}\n'
         '// Response: only token "unit" and "55" are generated; "IN" is discarded.\n'
         '```\n'
         '\n'
         '**Production Fix:**\n'
         'Use multi-fields with a raw `keyword` normalizer or a custom code analyzer:\n'
         '```json\n'
         'PUT /catalog\n'
         '{\n'
         '  "mappings": {\n'
         '    "properties": {\n'
         '      "model_number": {\n'
         '        "type": "text",\n'
         '        "analyzer": "standard",\n'
         '        "fields": {\n'
         '          "exact": {\n'
         '            "type": "keyword",\n'
         '            "normalizer": "lowercase_normalizer"\n'
         '          }\n'
         '        }\n'
         '      }\n'
         '    }\n'
         '  }\n'
         '}\n'
         '```\n'
         'Query using `term` or `multi_match` with a boost on `model_number.exact`:\n'
         '```json\n'
         'GET /catalog/_search\n'
         '{\n'
         '  "query": {\n'
         '    "multi_match": {\n'
         '      "query": "IT-100",\n'
         '      "fields": ["model_number", "model_number.exact^10"]\n'
         '    }\n'
         '  }\n'
         '}\n'
         '```'),
        ('Oversharding Primary Shard Imbalance and Latency Degradation',
         '# Index template creating 10 primary shards per daily index\n'
         'PUT /_index_template/daily_logs_template\n'
         '{\n'
         '  "index_patterns": ["logs-*"],\n'
         '  "template": {\n'
         '    "settings": {\n'
         '      "number_of_shards": 10,\n'
         '      "number_of_replicas": 1\n'
         '    }\n'
         '  }\n'
         '}\n'
         '# Daily index size: 500MB total per day.\n'
         '# After 180 days: 180 indices * 10 shards * 2 = 3,600 shards on a 3-node cluster.\n',
         'Search queries across last 30 days take 12,000ms. Heap memory on all 3 nodes is pegged at 95%. Elasticsearch '
         'crashes with frequent garbage collection pauses exceeding 10 seconds.',
         ["What is 'oversharding', and what memory overhead does each Lucene shard consume on the Java heap?",
          'What is the official Elasticsearch recommendation for shard size and shards per GB of heap?',
          'How do you remediate existing small shards using the Shrink API and Index Lifecycle Management (ILM)?'],
         '**Root Cause:**\n'
         'Each Lucene shard is an independent search engine with its own Lucene segment files, terms dictionaries, '
         'norms, and memory buffers. Even an empty or tiny shard consumes 4MB to 30MB of Java heap memory just to keep '
         'metadata and file handles open. With 3,600 shards on a 3-node cluster with 16GB heap per node, over 50% of '
         'the entire heap is consumed exclusively by shard overhead. When a query touches 30 daily indices ($30 \times '
         '10 = 300$ shards), it spawns 300 search tasks, saturating thread pools.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check shard count and heap overhead:\n'
         '   ```bash\n'
         '   GET /_cat/allocation?v\n'
         '   GET /_cat/shards?v&s=store:desc\n'
         '   ```\n'
         '2. Count total shards:\n'
         '   ```bash\n'
         '   GET /_cluster/health\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Elasticsearch Shard Sizing Rules:**\n'
         '   - Shard size should be between **20GB and 50GB**.\n'
         '   - Maintain fewer than **20 shards per GB of configured heap**. A node with 16GB heap should host at most '
         '300 shards.\n'
         '2. **Index Lifecycle Management (ILM) Rollover:**\n'
         '   Instead of daily calendar indices, roll over based on size:\n'
         '   ```json\n'
         '   PUT /_ilm/policy/logs_policy\n'
         '   {\n'
         '     "policy": {\n'
         '       "phases": {\n'
         '         "hot": {\n'
         '           "actions": {\n'
         '             "rollover": { "max_primary_shard_size": "30gb", "max_age": "30d" }\n'
         '           }\n'
         '         }\n'
         '       }\n'
         '     }\n'
         '   }\n'
         '   ```\n'
         '3. **Shrink and Merge Existing Shards:** Use the Shrink API (`POST '
         '/logs-2026-01-01/_shrink/logs-2026-01-01-shrunk`) to reduce 10 shards down to 1 shard for historical '
         'indices.')]}

