"""Diagnostic quiz questions, batch D: Modules 20-24 in Databases course.

Each entry is (title, code, symptom, questions, answer).
"""

from __future__ import annotations

DIAGNOSTICS: dict[str, list[tuple[str, str, str, list[str], str]]] = {'19': [('HNSW Recall Cliff from Undersized ef_search with Filtering',
         '-- pgvector table with HNSW index\n'
         'CREATE TABLE document_embeddings (\n'
         '    doc_id uuid PRIMARY KEY,\n'
         '    category_id int,\n'
         '    embedding vector(1536)\n'
         ');\n'
         '\n'
         'CREATE INDEX idx_docs_hnsw ON document_embeddings \n'
         'USING hnsw (embedding vector_cosine_ops) \n'
         'WITH (m = 16, ef_construction = 64);\n'
         '\n'
         '-- Query executed by semantic search API:\n'
         'SET hnsw.ef_search = 20;\n'
         '\n'
         'SELECT doc_id, embedding <=> $query_vector AS distance\n'
         'FROM document_embeddings\n'
         'WHERE category_id = 42\n'
         'ORDER BY distance\n'
         'LIMIT 10;\n',
         'Semantic search returns only 2 documents instead of requested 10, or returns documents with cosine distance '
         '0.85 when documents with cosine distance 0.12 exist in category 42.',
         ['Why does combining a restrictive `WHERE` filter with small `ef_search` cause an HNSW recall cliff?',
          'What is the difference between pre-filtering, post-filtering, and single-stage iterative HNSW index '
          'traversal?',
          'How should `ef_search` be tuned, or how does modern iterative index scanning resolve this issue?'],
         '**Root Cause:**\n'
         'In early vector search engines (and unoptimized HNSW implementations), post-filtering traverses the graph '
         'nearest-neighbor candidates first (bounded by `ef_search = 20`) and then filters out candidates that do not '
         'meet `category_id = 42`. If only 10% of total documents belong to category 42, an `ef_search` of 20 explores '
         'only 20 global nearest nodes, of which only 1 or 2 happen to match category 42, causing recall to collapse '
         'to near zero.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check execution plan in Postgres:\n'
         '   ```sql\n'
         '   EXPLAIN ANALYZE\n'
         '   SELECT doc_id FROM document_embeddings\n'
         '   WHERE category_id = 42\n'
         '   ORDER BY embedding <=> $query_vector LIMIT 10;\n'
         '   ```\n'
         '2. Observe whether pgvector used an index scan or filtered bitmap scan, and note the ratio of visited to '
         'returned nodes.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Increase `ef_search` dynamically for filtered queries:**\n'
         '   ```sql\n'
         '   SET hnsw.ef_search = 100;  -- or higher depending on filter selectivity\n'
         '   ```\n'
         '2. **Use pgvector 0.7.0+ Iterative Index Scan:** pgvector 0.7+ supports iterative index scans that '
         'dynamically continue traversing HNSW until the `LIMIT` is satisfied:\n'
         '   ```sql\n'
         "   SET hnsw.iterative_scan = 'relaxed';\n"
         '   ```\n'
         '3. **Payload Indexing in Qdrant:** In dedicated vector databases like Qdrant, build payload indexes on '
         '`category_id` so the HNSW traversal is restricted exclusively to nodes with `category_id = 42` during the '
         'graph traversal itself.'),
        ('Vector Normalization Mismatch in Cosine vs Inner Product Metric',
         '-- OpenAI text-embedding-3-small generates unit-normalized vectors (norm = 1.0)\n'
         '-- Custom BERT model generates unnormalized vectors (norm between 3.2 and 15.8)\n'
         '\n'
         'CREATE TABLE product_embeddings (\n'
         '    id serial PRIMARY KEY,\n'
         '    embedding vector(768)\n'
         ');\n'
         '\n'
         '-- Index built using Inner Product (<#>) for speed\n'
         'CREATE INDEX idx_products_ip ON product_embeddings \n'
         'USING ivfflat (embedding vector_ip_ops) WITH (lists = 100);\n'
         '\n'
         '-- Query using inner product:\n'
         'SELECT id FROM product_embeddings \n'
         'ORDER BY embedding <#> $query_vector LIMIT 5;\n',
         'Search returns completely irrelevant long documents first. Shorter, semantically identical product '
         'descriptions are ranked far down the list.',
         ['Why does Inner Product (`<#>`) return erroneous rankings when vectors are not unit-normalized?',
          'What is the mathematical relationship between Dot Product, Cosine Similarity, and Euclidean Distance for '
          'normalized vectors?',
          'How can you normalize vectors in SQL/Python or configure pgvector with native cosine distance (`<=>`)?'],
         '**Root Cause:**\n'
         'Inner product (dot product) between vectors $\\mathbf{u}$ and $\\mathbf{v}$ is defined as $\\mathbf{u} '
         '\\cdot \\mathbf{v} = \\|\\mathbf{u}\\| \\|\\mathbf{v}\\| \\cos(\theta)$. If vectors are not unit-normalized '
         '($\\|\\mathbf{u}\\| \n'
         'eq 1$), the metric is dominated by the vector magnitudes rather than the angle $\theta$. In embedding '
         'models, longer texts or documents with repeated terms often have larger $L_2$ norms, causing inner product '
         'to favor large-magnitude vectors over genuine semantic similarity.\n'
         '\n'
         '**Mathematical Proof:**\n'
         'Only when $\\|\\mathbf{u}\\| = 1$ and $\\|\\mathbf{v}\\| = 1$ does:\n'
         '$$\\mathbf{u} \\cdot \\mathbf{v} = \\cos(\theta) = 1 - \x0c'
         'rac{1}{2} \\|\\mathbf{u} - \\mathbf{v}\\|^2$$\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Option A: Use Cosine Distance (`<=>`) Index:**\n'
         '   ```sql\n'
         '   DROP INDEX idx_products_ip;\n'
         '   CREATE INDEX idx_products_cosine ON product_embeddings \n'
         '   USING hnsw (embedding vector_cosine_ops);\n'
         '   \n'
         '   SELECT id FROM product_embeddings ORDER BY embedding <=> $query_vector LIMIT 5;\n'
         '   ```\n'
         '2. **Option B: Normalize Vectors in Python Before Ingestion:**\n'
         '   ```python\n'
         '   import numpy as np\n'
         '   norm = np.linalg.norm(vec)\n'
         '   if norm > 0:\n'
         '       vec = vec / norm\n'
         '   # With unit-normalized vectors, inner product matches cosine similarity and is faster.\n'
         '   ```'),
        ('Uncompressed Flat Vector Index RAM Exhaustion',
         '# Ingesting 10,000,000 vectors of dimension 1536 (Float32) into Qdrant/pgvector\n'
         '# Server RAM: 64 GB\n'
         '\n'
         '# pgvector table:\n'
         'CREATE TABLE large_corpus (\n'
         '    id bigint PRIMARY KEY,\n'
         '    vector vector(1536)\n'
         ');\n'
         '-- 10 million vectors inserted\n'
         'CREATE INDEX idx_large_hnsw ON large_corpus \n'
         'USING hnsw (vector vector_cosine_ops) WITH (m = 32, ef_construction = 128);\n',
         'Postgres index build terminates after 3 hours with: out of memory. System OOM killer kills postgres process. '
         'In Qdrant, process crashes during index construction when memory exceeds 64GB.',
         ['How much RAM do 10 million 1536-dimensional Float32 vectors consume in raw storage plus HNSW graph edges?',
          'What is Scalar Quantization (SQ) and Product Quantization (PQ), and what compression ratios do they '
          'achieve?',
          'How can halfvec (Float16) or Product Quantization be enabled in pgvector / Qdrant to fit within RAM?'],
         '**Root Cause:**\n'
         'Let us calculate the memory requirement:\n'
         '1. **Raw Vectors:** $10,000,000 \times 1536 \times 4\text{ bytes} \x07pprox 61.44\text{ GB}$.\n'
         '2. **HNSW Graph Edges:** With $M = 32$, each node stores 32 neighbor pointers ($32 \times 8\text{ bytes} = '
         '256\text{ bytes}$ per vector) plus index metadata $\x07pprox 10\text{ to }15\text{ GB}$.\n'
         'Total memory required is over $75\text{ GB}$, exceeding the 64GB physical RAM limit. The system runs out of '
         'memory and crashes.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Scalar Quantization (SQ) / Float16 (`halfvec`):**\n'
         '   In `pgvector` 0.7+, use `halfvec` to cut vector storage by 50% (from 4 bytes to 2 bytes per float) with '
         'virtually zero recall loss:\n'
         '   ```sql\n'
         '   ALTER TABLE large_corpus ALTER COLUMN vector TYPE halfvec(1536);\n'
         '   -- Raw vectors drop from 61.4 GB to 30.7 GB\n'
         '   ```\n'
         '2. **Product Quantization (PQ) in Qdrant:**\n'
         '   Quantize 1536 floats into 96 or 192 byte codes (32x compression), storing quantized vectors in RAM and '
         'keeping original vectors on NVMe disk:\n'
         '   ```json\n'
         '   {\n'
         '     "quantization_config": {\n'
         '       "scalar": {\n'
         '         "type": "int8",\n'
         '         "quantile": 0.99,\n'
         '         "always_ram": true\n'
         '       }\n'
         '     }\n'
         '   }\n'
         '   ```\n'
         '   Memory drops from 75GB to ~12GB with 98%+ recall.'),
        ('Post-Filtering vs Single-Stage Filtered Vector Search Latency',
         '-- Hybrid query: find documents by author and semantic similarity\n'
         'SELECT doc_id, title\n'
         'FROM articles\n'
         "WHERE author_id = 'auth_10928'\n"
         'ORDER BY embedding <=> $search_vector\n'
         'LIMIT 5;\n'
         '\n'
         "-- articles contains 20,000,000 rows. author_id 'auth_10928' has only 8 articles.\n",
         'Query takes 14,200ms to execute. EXPLAIN ANALYZE shows an HNSW index scan visited 500,000 nodes before '
         'finding 5 matching the author filter.',
         ['Why does an HNSW index scan struggle when the relational filter matches a tiny fraction (<0.01%) of rows?',
          'When should the database optimizer choose a B-Tree index scan over a Vector index scan?',
          'How can you structure the index or query so Postgres uses the B-Tree index on `author_id` and exact '
          'distance calculation?'],
         '**Root Cause:**\n'
         'When a filter is highly selective (e.g. author 10928 has only 8 rows out of 20,000,000, or 0.00004%), '
         'searching through the global HNSW graph requires traversing hundreds of thousands of unrelated nodes just to '
         'stumble upon one belonging to that author. The CBO miscalculated costs and chose the HNSW index scan instead '
         'of a simple B-Tree index scan on `author_id` followed by an exact top-K distance sort on the 8 matching '
         'rows.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run `EXPLAIN (ANALYZE, BUFFERS)`:\n'
         '   ```sql\n'
         '   EXPLAIN (ANALYZE, BUFFERS)\n'
         "   SELECT doc_id FROM articles WHERE author_id = 'auth_10928'\n"
         '   ORDER BY embedding <=> $search_vector LIMIT 5;\n'
         '   ```\n'
         '2. Notice `HNSW index scan: loops=1, rows=5, time=14180ms`.\n'
         '\n'
         '**Production Fix:**\n'
         '1. Create a composite B-Tree index on `author_id`:\n'
         '   ```sql\n'
         '   CREATE INDEX idx_articles_author ON articles(author_id);\n'
         '   ```\n'
         '2. For highly selective filters, force the optimizer or write a CTE that isolates the small filtered '
         'candidate set first:\n'
         '   ```sql\n'
         '   WITH author_docs AS (\n'
         '       SELECT doc_id, embedding\n'
         '       FROM articles\n'
         "       WHERE author_id = 'auth_10928'  -- Uses B-Tree, fetches 8 rows in 0.1ms\n"
         '   )\n'
         '   SELECT doc_id\n'
         '   FROM author_docs\n'
         '   ORDER BY embedding <=> $search_vector\n'
         '   LIMIT 5;  -- Exact distance calculation on 8 rows takes 0.02ms\n'
         '   ```\n'
         '   Query latency drops from 14,000ms to **0.3ms**.'),
        ('Postgres WAL Amplification During HNSW Index Build',
         '-- Building HNSW index on 2 million 768-dim vectors\n'
         'CREATE INDEX idx_hnsw_embed ON items USING hnsw (embedding vector_cosine_ops);\n',
         'During index creation, disk space drops by 85 GB. Postgres replica falls 45 minutes behind. WAL archive '
         'directory fills up, causing database to stall all write transactions.',
         ['Why does building an HNSW or IVFFlat index generate enormous volumes of Write-Ahead Log (WAL)?',
          'What postgresql.conf settings (`wal_level`, `max_wal_size`, `maintenance_work_mem`) influence index build '
          'WAL generation?',
          'How can you build large vector indexes safely without saturating WAL archives or replicas?'],
         '**Root Cause:**\n'
         'In PostgreSQL, every page modification during index construction must be logged to WAL to guarantee crash '
         'recovery and replica replication. For HNSW, inserting millions of vectors requires building bi-directional '
         'graph links across multiple layers, dirtying thousands of index pages repeatedly. If `maintenance_work_mem` '
         'is low, Postgres must write temporary spill pages to disk and emit full-page WAL images, resulting in '
         '50GB–100GB of WAL generation for a 10GB dataset.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check WAL generation rate:\n'
         '   ```bash\n'
         "   SELECT pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), '0/00000000'));\n"
         '   ```\n'
         '2. Check replication lag on replica:\n'
         '   ```sql\n'
         '   SELECT client_addr, pg_wal_lsn_diff(pg_current_wal_lsn(), write_lsn) AS write_lag_bytes FROM '
         'pg_stat_replication;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Increase `maintenance_work_mem`:**\n'
         '   ```sql\n'
         "   SET maintenance_work_mem = '8GB';  -- Keep HNSW build graph in memory\n"
         '   ```\n'
         '2. **Increase `max_parallel_maintenance_workers`:**\n'
         '   ```sql\n'
         '   SET max_parallel_maintenance_workers = 4;\n'
         '   ```\n'
         '3. **If Populating a New Table:** Build the index *before* streaming WAL to replicas, or populate data with '
         '`UNLOGGED` table mode, build the index, and then convert to logged (`ALTER TABLE items SET LOGGED;`).\n'
         '4. **Tune WAL Checkpoint:** Increase `max_wal_size = 32GB` and `checkpoint_completion_target = 0.9` during '
         'large bulk index migrations.')],
 '20': [('Slotted Page Fragmentation and Table Bloat from Variable-Length Updates',
         '-- PostgreSQL table storing variable-length JSON documents\n'
         'CREATE TABLE user_sessions (\n'
         '    session_id uuid PRIMARY KEY,\n'
         '    user_id bigint,\n'
         '    metadata text  -- Initially 50 bytes, updated to 800 bytes frequently\n'
         ');\n'
         '\n'
         '-- Application performs 500 UPDATEs per second on existing session_ids:\n'
         'UPDATE user_sessions SET metadata = $new_expanded_json WHERE session_id = $id;\n',
         'Table size grows from 500 MB to 48 GB over 48 hours, even though the total number of active sessions remains '
         'fixed at 200,000. Read queries become 15x slower due to excessive page reads.',
         ['How does a slotted page (page layout with line pointers and tuple data) handle row updates that outgrow '
          'available page free space?',
          'What is HOT (Heap-Only Tuples) optimization in Postgres, and why did these updates fail to qualify for HOT?',
          'How do you diagnose table bloat and tune `fillfactor` and `autovacuum` to prevent page fragmentation?'],
         '**Root Cause:**\n'
         'In a slotted page architecture, a page header stores array pointers (line pointers) pointing to row offsets '
         'at the end of the 8KB page. When a row is updated in Postgres (MVCC), a new tuple version is created. If the '
         'updated row is larger than the remaining contiguous free space in the 8KB slotted page, Postgres cannot keep '
         'the new version on the same page. It must insert the new tuple onto a completely different page and update '
         'index pointers. Because `fillfactor` was 100% and rows expanded significantly, HOT optimization failed, '
         'resulting in massive heap fragmentation and dead tuple bloat.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check HOT update ratio:\n'
         '   ```sql\n'
         '   SELECT relname, n_tup_upd, n_tup_hot_upd,\n'
         '          round(100.0 * n_tup_hot_upd / nullif(n_tup_upd, 0), 2) AS hot_ratio\n'
         "   FROM pg_stat_user_tables WHERE relname = 'user_sessions';\n"
         '   -- hot_ratio near 0% indicates failure to use Heap-Only Tuples.\n'
         '   ```\n'
         '2. Inspect bloat using `pgstattuple`:\n'
         '   ```sql\n'
         "   SELECT * FROM pgstattuple('user_sessions');\n"
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Lower `fillfactor`:** Leave free space on each 8KB page for updates to expand in-place without page '
         'jumping:\n'
         '   ```sql\n'
         '   ALTER TABLE user_sessions SET (fillfactor = 70);\n'
         '   VACUUM FULL user_sessions;  -- Reclaim fragmented pages\n'
         '   ```\n'
         '2. **Aggressive Autovacuum:** Tune autovacuum to clean dead tuples continuously:\n'
         '   ```sql\n'
         '   ALTER TABLE user_sessions SET (\n'
         '       autovacuum_vacuum_scale_factor = 0.05,\n'
         '       autovacuum_vacuum_cost_limit = 1000\n'
         '   );\n'
         '   ```'),
        ('B+ Tree Rightmost Leaf Latch Contention on Auto-Increment Primary Keys',
         'CREATE TABLE telemetry_events (\n'
         '    id BIGSERIAL PRIMARY KEY,  -- Monotonically increasing sequence\n'
         '    device_id INT,\n'
         '    event_payload JSONB\n'
         ');\n'
         '\n'
         '-- 64 concurrent worker threads executing high-frequency concurrent INSERTs:\n'
         'INSERT INTO telemetry_events (device_id, event_payload) VALUES ($1, $2);\n',
         'Throughput plateaus at 8,000 inserts/sec despite high-end 64-core NVMe server. CPU utilization sits at 25% '
         'while threads spend 75% of their time waiting on LWLock (buffer_content / buf_mapping).',
         ['Why do monotonically increasing sequential keys create a physical concurrency bottleneck in B+ Trees?',
          'What is latch contention on the rightmost leaf page of a B+ Tree?',
          'What primary key design patterns (such as reverse-key indexes, hash partitioning, or UUIDv7 with salt) '
          'relieve latch contention?'],
         '**Root Cause:**\n'
         'In a B+ Tree, keys are kept strictly in sorted order. When using an auto-incrementing integer or sequential '
         'timestamp as the primary key, every single insert carries a key strictly greater than all existing keys. '
         'Consequently, 100% of concurrent insert transactions must acquire an exclusive write latch on the **exact '
         'same rightmost leaf page** of the B+ Tree. All 64 threads serialize behind this single 8KB page lock, '
         'resulting in massive latch contention and lock wait queues.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check wait events in `pg_stat_activity`:\n'
         '   ```sql\n'
         '   SELECT wait_event_type, wait_event, count(*)\n'
         '   FROM pg_stat_activity\n'
         "   WHERE state = 'active'\n"
         '   GROUP BY wait_event_type, wait_event;\n'
         "   -- Look for 'BufferContent' or 'BufferMapping' locks.\n"
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Hash Partitioning:** Partition the table across multiple physical B+ Trees using `PARTITION BY HASH '
         '(device_id)` with 16 or 32 partitions. Each partition has its own rightmost leaf page, spreading latch '
         'acquisition across 32 pages.\n'
         '2. **Scatter Keys:** Prepend a random shard prefix or tenant ID to the key:\n'
         '   ```sql\n'
         "   id = (shard_id << 48) | nextval('telemetry_seq')\n"
         '   ```\n'
         '3. **Application-Side Micro-Batching:** Insert multi-row batches (`INSERT INTO ... VALUES (...), (...), '
         '(...)`) so a single latch acquisition writes 100 rows rather than acquiring and releasing the latch 100 '
         'times.'),
        ('Dirty Page Writeback Starvation and Checkpoint Flush Avalanche',
         '# postgresql.conf\n'
         'shared_buffers = 32GB\n'
         'max_wal_size = 1GB\n'
         'checkpoint_timeout = 5min\n'
         'checkpoint_completion_target = 0.1  # Fast checkpoint flush\n',
         'Every 5 minutes, query throughput plummets to near zero for 20 seconds. Disk write bandwidth spikes to 2.5 '
         'GB/s, saturating storage controller and causing client timeouts.',
         ['What occurs during a database checkpoint, and why did this configuration create a flush avalanche?',
          'What role does the background writer (`bgwriter`) play in smoothing out buffer pool writeback?',
          'How should `max_wal_size`, `checkpoint_timeout`, and `checkpoint_completion_target` be configured for '
          'smooth I/O?'],
         '**Root Cause:**\n'
         'A **checkpoint** flushes all dirty buffer pool pages modified prior to the checkpoint LSN to disk so the WAL '
         'can be safely recycled. With `checkpoint_completion_target = 0.1` and `checkpoint_timeout = 5min`, Postgres '
         'attempts to flush all gigabytes of accumulated dirty pages within the first 10% of the interval (30 '
         'seconds). This floods the storage controller with an enormous burst of I/O writes, starving regular '
         'transaction query processing and WAL writes. Furthermore, `max_wal_size = 1GB` is too small for heavy write '
         'workloads, triggering checkpoints prematurely.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect checkpoint statistics in `pg_stat_bgwriter`:\n'
         '   ```sql\n'
         '   SELECT checkpoints_timed, checkpoints_req, checkpoint_write_time, checkpoint_sync_time, '
         'buffers_checkpoint\n'
         '   FROM pg_stat_bgwriter;\n'
         '   -- High checkpoints_req indicates max_wal_size is being exceeded before timeout.\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Spread Checkpoint I/O Evenly:** Set `checkpoint_completion_target = 0.9`. This instructs Postgres to '
         'spread the dirty page writes smoothly over 90% of the checkpoint interval:\n'
         '   ```conf\n'
         '   checkpoint_timeout = 15min\n'
         '   checkpoint_completion_target = 0.9\n'
         '   max_wal_size = 16GB\n'
         '   min_wal_size = 2GB\n'
         '   ```\n'
         '2. **Tune Background Writer:** Enable `bgwriter` to proactively flush dirty buffers ahead of server '
         'demands:\n'
         '   ```conf\n'
         '   bgwriter_delay = 20ms\n'
         '   bgwriter_lru_maxpages = 200\n'
         '   bgwriter_lru_multiplier = 3.0\n'
         '   ```'),
        ('Double-Write Buffer and WAL Write Amplification in Crash Recovery',
         '# MySQL InnoDB Configuration\n'
         'innodb_doublewrite = 1\n'
         'innodb_flush_log_at_trx_commit = 1\n'
         'sync_binlog = 1\n'
         '\n'
         '# Workload: 10,000 tiny single-row updates/sec (updating a 4-byte counter)\n',
         'Storage write throughput shows 180 MB/s of physical disk writes, even though user data changes account for '
         'only 40 KB/s. SSD wear-out indicators advance rapidly.',
         ["What is the 'torn page' problem in database storage engines, and why does MySQL use a Doublewrite Buffer?",
          'Why does a 4-byte update generate multiple 16KB page writes across WAL, binlog, and doublewrite buffer?',
          'How do modern filesystems (ZFS/ext4 with O_DIRECT) or atomic write SSDs allow safely disabling doublewrite '
          'buffers?'],
         '**Root Cause:**\n'
         'Operating system and disk sector sizes are typically 512 bytes or 4KB, whereas database pages are 16KB '
         '(InnoDB) or 8KB (PostgreSQL). If a crash occurs in the middle of writing a 16KB page to disk, the page is '
         'left half-written—a **torn page**—which corrupts the B+ Tree structure beyond recovery by normal WAL replay. '
         'To prevent this, InnoDB first writes the complete page to a contiguous **Doublewrite Buffer** on disk before '
         'writing it to its physical table location. Thus, a tiny 4-byte update writes: (1) Redo log buffer + fsync, '
         '(2) Binary log + fsync, (3) 16KB to Doublewrite buffer, (4) 16KB to table tablespace $\x07pprox$ massive '
         'write amplification.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check InnoDB doublewrite metrics:\n'
         '   ```sql\n'
         "   SHOW GLOBAL STATUS LIKE 'Innodb_dblwr%';\n"
         '   -- Innodb_dblwr_pages_written vs Innodb_pages_written\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Use Atomic Writes (if supported):** Modern NVMe SSDs or enterprise storage controllers (like AWS EBS or '
         'ZFS filesystems with copy-on-write semantics) provide atomic 16KB block writes. On these systems, torn pages '
         'are physically impossible:\n'
         '   ```cnf\n'
         '   innodb_doublewrite = 0\n'
         '   ```\n'
         '2. **Batch Updates / Group Commits:** Allow MySQL to flush multiple transactions in a single fsync via group '
         'commit, drastically reducing WAL fsync calls.'),
        ('Dangling Buffer Pool Row Pointer and Pin Count Race Condition',
         '// C / C++ Custom Storage Engine implementation\n'
         'void* fetch_row(PageId page_id, int slot_id) {\n'
         '    Page* page = buffer_pool.get_page(page_id); // Acquires latch, increments pin count\n'
         '    Row* row = page->get_row_ptr(slot_id);\n'
         '    buffer_pool.unpin(page_id);                  // Pin count decremented to 0\n'
         '    return row;                                 // Returns raw memory pointer\n'
         '}\n'
         '\n'
         'void worker_thread() {\n'
         '    Row* row = fetch_row(104, 3);\n'
         '    do_slow_computation();                      // Takes 50ms\n'
         '    printf("User balance: %d\\n", row->balance);  // Read from pointer\n'
         '}\n',
         'Intermittent segmentation faults or corrupted data printed under high concurrency. balance randomly prints '
         'garbage integers or negative values.',
         ["What is the purpose of 'pinning' a page in a buffer pool manager?",
          "What happens when a page's pin count drops to 0 while an application thread still holds a pointer to its "
          'memory?',
          'How must cursor lifetime, page latching, and page pinning be structured to guarantee memory safety?'],
         '**Root Cause:**\n'
         'In a buffer pool manager, **pinning** a page (`pin_count > 0`) informs the buffer eviction algorithm (LRU, '
         'CLOCK, or 2Q) that the page is currently being accessed and **must not be evicted or replaced**. The '
         'function `fetch_row` unpins the page immediately upon return. During `do_slow_computation()`, another thread '
         'requests a new page, and the buffer eviction algorithm selects Page 104 (since `pin_count == 0`), '
         'overwriting its memory frame with completely different data from disk. When `worker_thread` subsequently '
         'accesses `row->balance`, it reads garbage memory from the new page (use-after-free / eviction race).\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run with AddressSanitizer (ASan) or Valgrind:\n'
         '   `AddressSanitizer: heap-use-after-free` or invalid memory read.\n'
         '2. Log buffer eviction events matching `page_id == 104`.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Hold Pin for Lifetime of Access:** The worker thread must hold the pin until it is finished reading the '
         'tuple:\n'
         '   ```cpp\n'
         '   PageHandle handle = buffer_pool.pin_page(page_id);\n'
         '   Row* row = handle.get_page()->get_row(slot_id);\n'
         '   // Read data or copy to local struct\n'
         '   int balance = row->balance;\n'
         '   handle.release(); // Unpins page\n'
         '   ```\n'
         '2. **Copy on Access:** If computation is long, deserialize or copy the row data into a thread-local object '
         'and immediately release the buffer pool page lock and pin.')],
 '21': [('Stale Statistics Causing Optimizer to Choose Nested Loop over Hash Join',
         "-- Table 'orders' grew from 1,000 rows to 15,000,000 rows after bulk import\n"
         "-- Table 'customers' has 500,000 rows\n"
         '\n'
         'SELECT c.customer_name, sum(o.total_amount)\n'
         'FROM customers c\n'
         'JOIN orders o ON c.customer_id = o.customer_id\n'
         "WHERE c.country = 'Germany'\n"
         'GROUP BY c.customer_name;\n',
         'Query previously ran in 400ms. Following the bulk import, the query runs for 48 minutes with 100% '
         'single-core CPU utilization.',
         ['Why did the Cost-Based Optimizer (CBO) choose a Nested Loop join instead of a Hash Join or Merge Join?',
          'How does `EXPLAIN (ANALYZE)` reveal estimation errors (rows=... estimated vs actual)?',
          'What maintenance command updates catalog statistics, and how do you configure autovacuum analyze '
          'thresholds?'],
         '**Root Cause:**\n'
         'The Cost-Based Optimizer relies on table statistics in `pg_statistic` (or `pg_class.reltuples`). Before the '
         'bulk import, `orders` had only 1,000 rows, for which a Nested Loop join is the lowest-cost plan. Because '
         'autovacuum/analyze had not yet executed after the bulk import, the planner believed `orders` still contained '
         'only 1,000 rows. In reality, scanning 15,000,000 rows in an unindexed or index-driven nested loop results in '
         '$50,000 \times 15,000,000$ index/heap evaluations, turning a sub-second Hash Join into a 48-minute '
         'disaster.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run `EXPLAIN ANALYZE`:\n'
         '   ```sql\n'
         '   EXPLAIN ANALYZE SELECT ...;\n'
         '   ```\n'
         '   Look for: `Nested Loop (cost=... rows=10 width=...) (actual time=... rows=4500000)`. Notice the 1000x '
         'disparity between estimated rows and actual rows.\n'
         '2. Check last analyze timestamp:\n'
         '   ```sql\n'
         '   SELECT relname, last_analyze, last_autoanalyze, reltuples FROM pg_stat_user_tables WHERE relname = '
         "'orders';\n"
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Immediate Fix:** Run `ANALYZE` immediately after large bulk inserts or data migrations:\n'
         '   ```sql\n'
         '   ANALYZE orders;\n'
         '   ANALYZE customers;\n'
         '   ```\n'
         '2. **Tune Auto-Analyze Thresholds:** For large tables, default 10% change thresholds take too long to '
         'trigger. Lower the threshold:\n'
         '   ```sql\n'
         '   ALTER TABLE orders SET (autovacuum_analyze_scale_factor = 0.02); -- Trigger at 2% changes\n'
         '   ```'),
        ('Missing Foreign Key Index Causing Table ShareLock Deadlocks',
         'CREATE TABLE departments (\n'
         '    dept_id serial PRIMARY KEY,\n'
         '    name text\n'
         ');\n'
         '\n'
         'CREATE TABLE employees (\n'
         '    emp_id serial PRIMARY KEY,\n'
         '    dept_id int REFERENCES departments(dept_id) ON DELETE CASCADE,\n'
         '    name text\n'
         ');\n'
         '-- Note: dept_id in employees is NOT indexed!\n'
         '\n'
         '-- Transaction 1:\n'
         'DELETE FROM departments WHERE dept_id = 5;\n'
         '\n'
         '-- Concurrent Transaction 2:\n'
         "UPDATE employees SET name = 'Bob' WHERE emp_id = 9921;\n",
         'Deleting a department blocks all updates to the employees table. Concurrently executing transactions fail '
         'with: ERROR: deadlock detected, or queries time out after waiting on ShareLock.',
         ['Why does a foreign key without an index cause table-level locks or sequential scans during parent key '
          'updates/deletes?',
          'Does PostgreSQL automatically create indexes on Foreign Key columns?',
          'What SQL query finds all unindexed foreign keys across the entire database schema?'],
         '**Root Cause:**\n'
         'Unlike primary keys and unique constraints, **foreign key columns are NOT automatically indexed in '
         'PostgreSQL** (or MySQL). When a row in `departments` is deleted or its primary key updated, the database '
         'must check the `employees` table to enforce referential integrity (`ON DELETE CASCADE` or `RESTRICT`). '
         'Without an index on `employees(dept_id)`, Postgres must perform a **full sequential scan** of the entire '
         '`employees` table while holding a restrictive table lock (`ShareRowExclusiveLock` or `RowShareLock`), '
         'blocking all concurrent modifications and causing severe deadlock cycles.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Find unindexed foreign keys in PostgreSQL:\n'
         '   ```sql\n'
         '   SELECT c.conrelid::regclass AS table_name,\n'
         "          string_agg(a.attname, ', ') AS fk_columns,\n"
         '          c.conname\n'
         '   FROM pg_constraint c\n'
         '   JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)\n'
         "   WHERE c.contype = 'f'\n"
         '     AND NOT EXISTS (\n'
         '       SELECT 1 FROM pg_index i\n'
         '       WHERE i.indrelid = c.conrelid\n'
         '         AND c.conkey = i.indkey[0:array_length(c.conkey, 1) - 1]\n'
         '     )\n'
         '   GROUP BY c.conrelid, c.conname;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         'Create an explicit index on all foreign key referencing columns:\n'
         '```sql\n'
         'CREATE INDEX CONCURRENTLY idx_employees_dept_id ON employees(dept_id);\n'
         '```\n'
         'With the index present, cascade deletes and integrity checks perform an instant index seek without locking '
         'the entire table.'),
        ('Function-Wrapped Column Preventing B-Tree Index Scan',
         'CREATE TABLE users (\n'
         '    id serial PRIMARY KEY,\n'
         '    email text,\n'
         '    created_at timestamp\n'
         ');\n'
         '\n'
         'CREATE INDEX idx_users_email ON users(email);\n'
         '\n'
         '-- Query executed by authentication service:\n'
         "SELECT id, email FROM users WHERE LOWER(email) = 'john.doe@example.com';\n",
         "Query latency is 850ms on a table of 10 million users. EXPLAIN shows: 'Seq Scan on users "
         "(cost=0.00..284100.00 rows=50000)' instead of using idx_users_email.",
         ['Why cannot a standard B-Tree index on `email` be used when the query wraps the column in `LOWER(email)`?',
          'What is an Expression / Functional Index in relational databases?',
          'What DDL statement creates the necessary functional index or column collation to enable index seeks?'],
         '**Root Cause:**\n'
         'A standard B-Tree index on `email` stores the exact raw string bytes sorted in binary or collation order '
         "(e.g. `'John.Doe@example.com'`). When a query evaluates `WHERE LOWER(email) = ...`, the index does not "
         'contain precomputed lowercased values. The database cannot predict the mathematical behavior of arbitrary '
         'functions across index nodes and is forced to perform a full sequential scan of all 10 million rows, '
         'computing `LOWER()` on every single row.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run `EXPLAIN` to confirm sequential scan:\n'
         '   ```sql\n'
         "   EXPLAIN SELECT id FROM users WHERE LOWER(email) = 'john.doe@example.com';\n"
         "   -- Filter: (lower(email) = 'john.doe@example.com'::text)\n"
         '   -- Rows Removed by Filter: 9999999\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Option A: Create an Expression Index:**\n'
         '   ```sql\n'
         '   CREATE INDEX CONCURRENTLY idx_users_lower_email ON users(LOWER(email));\n'
         '   ```\n'
         "   Now `WHERE LOWER(email) = '...'` performs an instant B-Tree Index Scan ($< 0.5\text{ ms}$).\n"
         '2. **Option B: Use `citext` (Case-Insensitive Text Type):**\n'
         '   ```sql\n'
         '   CREATE EXTENSION IF NOT EXISTS citext;\n'
         '   ALTER TABLE users ALTER COLUMN email TYPE citext;\n'
         '   CREATE INDEX idx_users_email ON users(email);\n'
         '   ```\n'
         "   Any query `WHERE email = 'John.Doe@example.com'` is automatically case-insensitive and uses the index "
         'natively.'),
        ('Data Skew and Histogram Bucket Misestimation on Tenant Queries',
         '-- Multi-tenant SaaS table\n'
         'CREATE TABLE audit_logs (\n'
         '    id bigserial PRIMARY KEY,\n'
         '    tenant_id int,\n'
         '    action text,\n'
         '    created_at timestamp\n'
         ');\n'
         '-- Tenant 1 (Mega-Enterprise): 45,000,000 rows (90% of table)\n'
         '-- Tenants 2 through 10,000 (Small clients): ~500 rows each\n'
         '\n'
         'CREATE INDEX idx_audit_tenant ON audit_logs(tenant_id);\n'
         '\n'
         '-- Query executed for Tenant 1:\n'
         "SELECT * FROM audit_logs WHERE tenant_id = 1 AND action = 'LOGIN';\n",
         'When querying tenant 1, Postgres chooses an Index Scan. The query performs 45,000,000 random disk seeks '
         'across the heap and takes 4 minutes, causing massive disk I/O thrashing.',
         ['Why is an Index Scan dramatically worse than a Sequential Scan when retrieving 90% of a table?',
          'How do Most Common Values (MCV) lists and histogram bounds guide optimizer decisions?',
          'How can you increase statistics target (`default_statistics_target`) or use partial indexes for skewed '
          'tenants?'],
         '**Root Cause:**\n'
         'An Index Scan visits the B-Tree index, retrieves physical tuple pointers (TIDs), and performs random I/O '
         'seeks into heap pages to fetch each row. When fetching 1% or less of a table, random seeks are efficient. '
         'But when fetching 45,000,000 rows (90% of the table), scanning the sequential table heap sequentially in '
         "128KB disk blocks is orders of magnitude faster than 45 million random seeks. If the optimizer's statistics "
         'target was too low, it failed to recognize that `tenant_id = 1` represents 90% of all data, incorrectly '
         'estimating low rows and selecting an Index Scan.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect MCV (Most Common Values) in `pg_stats`:\n'
         '   ```sql\n'
         '   SELECT most_common_vals, most_common_freqs\n'
         '   FROM pg_stats\n'
         "   WHERE tablename = 'audit_logs' AND attname = 'tenant_id';\n"
         '   ```\n'
         '2. Verify if `tenant_id = 1` is correctly recognized in MCV.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Increase Statistics Target for the Skewed Column:**\n'
         '   ```sql\n'
         '   ALTER TABLE audit_logs ALTER COLUMN tenant_id SET STATISTICS 1000;\n'
         '   ANALYZE audit_logs;\n'
         '   ```\n'
         '   This expands the MCV list from 100 to 1,000 entries and increases histogram resolution, allowing the CBO '
         'to select Sequential Scan or Bitmap Scan for tenant 1, and Index Scan for smaller tenants.\n'
         '2. **Partial Indexing:**\n'
         '   Index only the high-cardinality long-tail tenants:\n'
         '   ```sql\n'
         '   CREATE INDEX idx_audit_small_tenants ON audit_logs(tenant_id) WHERE tenant_id != 1;\n'
         '   ```'),
        ('Correlated Subquery Optimization Breakdown and Bitmap Scan Degeneracy',
         'SELECT p.product_id, p.product_name,\n'
         '       (SELECT avg(r.rating) \n'
         '        FROM reviews r \n'
         '        WHERE r.product_id = p.product_id \n'
         "          AND r.created_at >= CURRENT_DATE - INTERVAL '30 days') AS recent_rating\n"
         'FROM products p\n'
         'WHERE p.is_active = true;\n',
         'Query takes 3 minutes for 20,000 active products, even though `reviews` has an index on `(product_id, '
         'created_at)`. Database CPU runs at 100%.',
         ['What is a correlated subquery, and why does executing it in the `SELECT` clause cause $O(N)$ query loops?',
          'How can you view the subplan execution counts in `EXPLAIN ANALYZE`?',
          'How should this query be rewritten using a `LEFT JOIN` with pre-aggregation or a Lateral Join?'],
         '**Root Cause:**\n'
         'A scalar subquery placed in the `SELECT` projection list that references outer table columns '
         '(`p.product_id`) is a **correlated subquery**. In many query engines, this executes as a `SubPlan`: for '
         'every single row returned from `products` (20,000 active products), the subquery is invoked independently '
         '20,000 separate times. Even with an index, executing 20,000 individual index lookups and aggregation loops '
         'incurs severe execution overhead compared to a single set-based join.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run `EXPLAIN ANALYZE`:\n'
         '   ```sql\n'
         '   EXPLAIN ANALYZE SELECT ...;\n'
         '   ```\n'
         '   Look for: `SubPlan 1: SubPlan Loops: 20000`. The high loop count confirms row-by-row correlated '
         'execution.\n'
         '\n'
         '**Production Fix:**\n'
         'Rewrite the query as a set-based `LEFT JOIN` with a pre-aggregated Common Table Expression (CTE) or '
         'subquery:\n'
         '```sql\n'
         'SELECT p.product_id, p.product_name, r.recent_rating\n'
         'FROM products p\n'
         'LEFT JOIN (\n'
         '    SELECT product_id, avg(rating) AS recent_rating\n'
         '    FROM reviews\n'
         "    WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'\n"
         '    GROUP BY product_id\n'
         ') r ON p.product_id = r.product_id\n'
         'WHERE p.is_active = true;\n'
         '```\n'
         'Now both relations are scanned once and joined via a single Hash Join in **35ms** (a 5,000x speedup).')],
 '22': [('Write Skew Anomaly Under REPEATABLE READ Isolation',
         '-- Hospital Doctor On-Call Schedule Table\n'
         'CREATE TABLE on_call_schedule (\n'
         '    doctor_id int PRIMARY KEY,\n'
         '    doctor_name text,\n'
         '    is_on_call boolean\n'
         ');\n'
         '-- Constraint: At least ONE doctor must remain on call at all times!\n'
         '-- Current state: Alice and Bob are BOTH on call (is_on_call = true).\n'
         '\n'
         '-- Transaction 1 (Doctor Alice takes leave):\n'
         'BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;\n'
         'SELECT count(*) FROM on_call_schedule WHERE is_on_call = true; -- Returns 2\n'
         'UPDATE on_call_schedule SET is_on_call = false WHERE doctor_id = 1; -- Alice\n'
         'COMMIT;\n'
         '\n'
         '-- Concurrent Transaction 2 (Doctor Bob takes leave):\n'
         'BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;\n'
         'SELECT count(*) FROM on_call_schedule WHERE is_on_call = true; -- Returns 2\n'
         'UPDATE on_call_schedule SET is_on_call = false WHERE doctor_id = 2; -- Bob\n'
         'COMMIT;\n',
         'Both transactions commit successfully with 0 errors. Querying the table reveals ZERO doctors on call (both '
         'Alice and Bob set to false), violating the hospital invariant.',
         ['What is Write Skew, and why does REPEATABLE READ (Snapshot Isolation) fail to prevent it?',
          'Why was no row-level write-write lock conflict detected between Transaction 1 and Transaction 2?',
          'What are the two valid solutions: `SERIALIZABLE` isolation level vs explicit pessimistic locking (`SELECT '
          '... FOR UPDATE`)?'],
         '**Root Cause:**\n'
         '**Write Skew** occurs under Snapshot Isolation / REPEATABLE READ when two concurrent transactions read '
         "overlapping datasets (both see 2 doctors on call) but make disjoint mutations (Tx 1 updates Alice's row; Tx "
         "2 updates Bob's row). Because the two transactions modified different physical rows, there was no "
         'write-write conflict to trigger a rollback. Each transaction made an assumption based on a premise that the '
         'other transaction simultaneously invalidated, breaking the global invariant.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Reproduce under `REPEATABLE READ`: Both commit without errors.\n'
         '2. Check transaction isolation level:\n'
         '   ```sql\n'
         '   SHOW transaction_isolation;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '- **Approach 1 (SERIALIZABLE Isolation):** Use true `SERIALIZABLE` isolation (SSI / Serializable Snapshot '
         'Isolation in Postgres):\n'
         '  ```sql\n'
         '  BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;\n'
         '  ```\n'
         '  Postgres tracks read-write dependencies (SIREAD locks). Transaction 2 will fail with: `ERROR: could not '
         'serialize access due to read/write dependencies among transactions`.\n'
         '- **Approach 2 (Pessimistic Locking / Materialized Conflict):**\n'
         '  Lock the entire group or use `FOR UPDATE` on all on-call records:\n'
         '  ```sql\n'
         '  SELECT count(*) FROM on_call_schedule WHERE is_on_call = true FOR UPDATE;\n'
         '  ```\n'
         '  Tx 2 will block until Tx 1 commits, then re-read `count = 1` and abort.'),
        ('Two-Phase Commit (2PC) Participant In-Doubt Blocking on Coordinator Crash',
         '# Two-Phase Commit Distributed Transaction\n'
         '# Coordinator coordinates Bank DB 1 and Bank DB 2\n'
         '\n'
         '# Phase 1 (Prepare):\n'
         'coord.send_prepare(DB1, "tx_991") # DB1 replies: PREPARED\n'
         'coord.send_prepare(DB2, "tx_991") # DB2 replies: PREPARED\n'
         '\n'
         '# Coordinator writes "COMMIT" to local WAL... and immediately suffers POWER FAILURE!\n'
         '# Coordinator remains offline for 6 hours.\n',
         'Bank DB 1 and DB 2 have dozens of customer account rows completely locked. All incoming user transactions '
         'attempting to read or update those accounts hang indefinitely and time out.',
         ["What is the 'In-Doubt' state in Two-Phase Commit (2PC)?",
          'Why cannot a 2PC participant unilaterally decide to commit or abort while in the Prepared state?',
          'How does Three-Phase Commit (3PC) or Paxos/Raft-backed transaction coordinators eliminate coordinator '
          'single-point-of-failure blocking?'],
         '**Root Cause:**\n'
         'Once a 2PC participant votes `PREPARED`, it enters the **In-Doubt** state. It has promised the coordinator '
         'that it can and will either commit or abort whenever instructed, and holds exclusive row locks on the '
         'modified data to uphold ACID guarantees. The participant **cannot unilaterally abort** (because the '
         'coordinator might have decided to commit and told other participants to commit), nor can it **unilaterally '
         'commit** (because another participant might have voted abort). It is completely blocked until the '
         'coordinator recovers and tells it the outcome.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check prepared transactions in PostgreSQL:\n'
         '   ```sql\n'
         '   SELECT gid, prepared, owner, database FROM pg_prepared_xacts;\n'
         '   ```\n'
         '2. Check locks held by prepared transactions:\n'
         '   ```sql\n'
         '   SELECT * FROM pg_locks WHERE transactionid IS NOT NULL;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Manual Administrator Recovery:** Inspect coordinator logs. If coordinator committed, manually commit '
         'the prepared transaction:\n'
         '   ```sql\n'
         "   COMMIT PREPARED 'tx_991';\n"
         '   -- Or if coordinator aborted:\n'
         "   ROLLBACK PREPARED 'tx_991';\n"
         '   ```\n'
         '2. **Modern Architecture Fix:** Replace traditional 2PC coordinators with a replicated state machine backed '
         'by **Raft or Paxos** (e.g. CockroachDB, Spanner, or Temporal). In these systems, coordinator state is '
         'replicated across a consensus group; if the active coordinator crashes, a new leader takes over immediately '
         'and finishes in-doubt transactions within milliseconds.'),
        ('Raft Consensus Split-Vote Livelock from Homogeneous Election Timeouts',
         '# Raft Consensus Node Configuration (5-node cluster)\n'
         'heartbeat_interval = 100ms\n'
         'election_timeout_min = 200ms\n'
         'election_timeout_max = 200ms  # Fixed, non-randomized timeout!\n',
         'When the active Raft leader is killed, the cluster fails to elect a new leader. Term numbers rapidly '
         'increment from Term 1 to Term 840 in 2 minutes. The cluster remains completely unavailable for client '
         'writes.',
         ['Why does a fixed election timeout cause split votes in Raft?',
          'What is the quorum requirement for electing a leader in a 5-node cluster?',
          'How does randomized election timeout resolve split votes and guarantee quick leader convergence?'],
         '**Root Cause:**\n'
         'In Raft, a leader candidate must receive votes from a majority of nodes ($\\lfloor N/2 \r'
         'floor + 1 = 3$ in a 5-node cluster). When the current leader fails, all 4 remaining followers wait for their '
         'election timeout before starting an election. Because their election timeouts are identical (200ms), all 4 '
         'nodes transition to Candidate state and broadcast `RequestVote` RPCs at the exact same millisecond. Each '
         'node votes for itself first, splitting the votes ($1 + 1 + 1 + 1$). None achieve a 3-node majority. The term '
         'expires, they all restart elections simultaneously, repeating the split-vote loop indefinitely (**election '
         'livelock**).\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect Raft logs:\n'
         '   ```text\n'
         '   Node 2: Election timeout -> Starting election for Term 42\n'
         '   Node 3: Election timeout -> Starting election for Term 42\n'
         '   Node 2: Received 2 votes, required 3 -> Election failed\n'
         '   Node 3: Received 2 votes, required 3 -> Election failed\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         'Implement **Randomized Election Timeouts** as mandated by the Raft specification:\n'
         '```python\n'
         'import random\n'
         '\n'
         'heartbeat_interval = 100  # ms\n'
         '# Randomize election timeout between 150ms and 300ms\n'
         'election_timeout = random.uniform(150, 300)\n'
         '```\n'
         "With randomized timeouts, one node's timer will naturally expire before the others (e.g. at 162ms). It "
         'increments the term, votes for itself, and broadcasts `RequestVote` before other nodes timeout, securing '
         'votes from the other followers and establishing leadership in a single round.'),
        ('Raft Stale Read Anomaly During Asymmetric Network Partition',
         '# 5-Node Raft Cluster: Node 1 (Leader), Nodes 2, 3, 4, 5 (Followers)\n'
         '# Network partition occurs:\n'
         '# Partition A: Node 1 (Old Leader) isolated with Node 2\n'
         '# Partition B: Nodes 3, 4, 5 (Elected Node 3 as New Leader)\n'
         '\n'
         '# Client reads user balance from Node 1:\n'
         'balance = node1.read("account:user_42:balance")\n',
         'Client reads balance = $1,000 from Node 1, even though a write committing balance = $200 was successfully '
         'acknowledged by Node 3 (new leader) to another client 5 seconds ago.',
         ['Why can an isolated old Raft leader serve stale reads if it simply reads its local state machine?',
          'What is ReadIndex and Lease Read in Raft linearizable read semantics?',
          'How do you guarantee linearizable reads without running full Raft log consensus for every read query?'],
         '**Root Cause:**\n'
         'In Raft, writes require a majority quorum (3 out of 5 nodes), so Node 1 cannot commit new writes in '
         'Partition A. However, if read requests are served directly from the local state machine without checking '
         "current leadership status, an old leader that hasn't realized it has been deposed will continue serving "
         'stale data to clients until its election/heartbeat probe times out.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check current leader identity across nodes:\n'
         '   ```bash\n'
         '   curl http://node1:8001/raft/status  # Claims leader=Node 1, Term=5\n'
         '   curl http://node3:8001/raft/status  # Claims leader=Node 3, Term=6\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **ReadIndex Algorithm:**\n'
         '   When a read arrives at a leader:\n'
         '   - Leader records its current `commitIndex` as `readIndex`.\n'
         '   - Leader broadcasts a heartbeat round (`AppendEntries` with 0 logs) to followers and waits for a majority '
         'confirmation to verify it is still the legitimate leader.\n'
         '   - Once confirmed, the leader waits until its state machine applies up to `readIndex`, and then returns '
         'the data.\n'
         '2. **Leader Leases:** The leader maintains a bounded time lease renewed on successful heartbeats. Reads can '
         'be answered locally as long as the leader lease has not expired.'),
        ('Deadlock Cycle from Inconsistent Multi-Table Locking Order',
         '-- Transaction 1 (Payment Service):\n'
         'BEGIN;\n'
         "UPDATE accounts SET balance = balance - 100 WHERE account_id = 'acc_A';\n"
         '-- Does other processing...\n'
         "UPDATE accounts SET balance = balance + 100 WHERE account_id = 'acc_B';\n"
         'COMMIT;\n'
         '\n'
         '-- Concurrent Transaction 2 (Refund Service):\n'
         'BEGIN;\n'
         "UPDATE accounts SET balance = balance + 100 WHERE account_id = 'acc_B';\n"
         '-- Does other processing...\n'
         "UPDATE accounts SET balance = balance - 100 WHERE account_id = 'acc_A';\n"
         'COMMIT;\n',
         'Both transactions freeze for 1,000ms until one terminates with: ERROR: deadlock detected. Detail: Process '
         '2819 waits for ExclusiveLock on tuple (0, 12) of relation accounts; blocked by process 2820.',
         ['What are the four necessary conditions for deadlock (Coffman conditions)?',
          "How does PostgreSQL's deadlock detector identify deadlock cycles?",
          'How does enforcing a deterministic global lock ordering eliminate deadlocks by design?'],
         '**Root Cause:**\n'
         'A deadlock occurs when two or more transactions hold locks that the other needs and neither can proceed.\n'
         '- Tx 1 acquired an exclusive row lock on `acc_A` and requested a lock on `acc_B`.\n'
         '- Tx 2 acquired an exclusive row lock on `acc_B` and requested a lock on `acc_A`.\n'
         'Because the locks were acquired in reverse order (`A -> B` vs `B -> A`), a circular wait condition was '
         'created. After `deadlock_timeout` (default 1s), Postgres traces the dependency graph, detects the cycle, and '
         'aborts one transaction.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Examine PostgreSQL log file for the full deadlock dump:\n'
         '   ```text\n'
         "   Process 2819: UPDATE accounts ... WHERE account_id = 'acc_B';\n"
         "   Process 2820: UPDATE accounts ... WHERE account_id = 'acc_A';\n"
         '   ```\n'
         '2. Inspect `pg_stat_database` deadlock counter:\n'
         '   ```sql\n'
         '   SELECT datname, deadlocks FROM pg_stat_database;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Deterministic Lock Ordering:** Always acquire locks in a globally consistent, deterministic order (e.g. '
         'sorted by primary key):\n'
         '   ```python\n'
         '   def transfer(acc_from, acc_to, amount):\n'
         '       # Sort account IDs lexicographically:\n'
         '       first, second = sorted([acc_from, acc_to])\n'
         '       with db.transaction():\n'
         '           db.execute("SELECT * FROM accounts WHERE id = %s FOR UPDATE", (first,))\n'
         '           db.execute("SELECT * FROM accounts WHERE id = %s FOR UPDATE", (second,))\n'
         '           # Perform updates...\n'
         '   ```\n'
         '   Because all transactions lock `first` then `second`, circular waits are mathematically impossible.')],
 '23': [('Point-In-Time Recovery (PITR) Failure from WAL Segment Gap',
         '# Restoring production database from basebackup taken at 02:00 UTC\n'
         '# Target recovery time: 14:30 UTC\n'
         '# recovery.signal present in data directory:\n'
         "restore_command = 'cp /mnt/wal_archive/%f %p'\n"
         "recovery_target_time = '2026-09-08 14:30:00 UTC'\n",
         'Postgres recovery starts, replays up to 08:15 UTC, and abruptly stops with: FATAL: could not restore file '
         "'000000010000001B00000042' from archive: return code 1. Database starts in read-only recovery state at 08:15 "
         'UTC. 6 hours of business transactions are missing.',
         ['What is a WAL segment gap, and why does missing a single 16MB WAL file abort the entire recovery chain?',
          'How does `archive_command` fail silently if return codes are ignored or disks fill up?',
          'How do modern backup tools like pgBackRest / WAL-G prevent WAL gaps and verify archive integrity?'],
         '**Root Cause:**\n'
         'Point-In-Time Recovery (PITR) functions as a strictly sequential log replay. Every WAL segment contains a '
         "monotonically increasing log sequence number (LSN) and references the previous segment's end LSN. If WAL "
         'file `...42` was never archived (e.g. because the network dropped during `archive_command`, or the archive '
         'script did not return non-zero on failure), there is an unbridgeable **WAL gap**. Postgres cannot skip '
         'missing WAL files because subsequent WAL changes rely on physical page states produced by the missing '
         'segment.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check WAL archive logs:\n'
         '   ```bash\n'
         '   SELECT * FROM pg_stat_archiver;\n'
         '   -- Look for failed_count > 0 and last_failed_wal\n'
         '   ```\n'
         '2. Check continuity of files in `/mnt/wal_archive`:\n'
         '   ```bash\n'
         '   ls -1 /mnt/wal_archive | sort\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Never use naive `cp` or shell scripts for `archive_command`:** Naive shell commands often fail silently '
         'on disk full or permissions errors.\n'
         '2. **Use Enterprise Backup Tools (`pgBackRest` or `WAL-G`):**\n'
         '   - pgBackRest automatically validates WAL file checksums.\n'
         '   - It performs asynchronous, multi-threaded retries with backoff.\n'
         '   - It runs daily `archive-check` commands to verify that the WAL chain from the base backup to current LSN '
         'is 100% contiguous with zero gaps.'),
        ('Connection Pool Exhaustion and 503 Cascades on Backend Spike',
         '# postgresql.conf\n'
         'max_connections = 500\n'
         '\n'
         '# 50 web server instances, each running Gunicorn with 20 worker processes\n'
         '# No connection pooler (PgBouncer) between app and database.\n'
         '# Each worker connects directly to Postgres via psycopg2.\n',
         'During a marketing campaign, web traffic doubles. Database CPU spikes to 100%. Web applications throw: '
         'FATAL: remaining connection slots are reserved for non-replication superuser connections. Latency across all '
         'APIs spikes from 15ms to 30,000ms.',
         ['Why is running 1,000 direct connections to PostgreSQL disastrous for CPU performance?',
          'What is the memory footprint of an idle PostgreSQL backend process?',
          'How does configuring PgBouncer in transaction pooling mode resolve connection storms?'],
         '**Root Cause:**\n'
         'PostgreSQL uses a process-per-connection model (`fork()`). Each backend connection consumes 5MB to 20MB of '
         'RAM just for process state, plus private catalog caches. More critically, having 1,000 concurrent active '
         'processes causes devastating **CPU context switching** and latch contention across shared memory structures '
         '(`ProcArrayLock`, buffer mapping tables). A 16-core server performs optimally with only 30 to 60 truly '
         'active query threads. When 1,000 workers contend simultaneously, the CPU spends 90% of cycles switching '
         'tasks rather than executing SQL.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check active connection states:\n'
         '   ```sql\n'
         '   SELECT state, count(*) FROM pg_stat_activity GROUP BY state;\n'
         "   -- Notice 850 connections in 'idle' or 'idle in transaction'.\n"
         '   ```\n'
         '2. Monitor context switches:\n'
         '   ```bash\n'
         "   vmstat 1  # Look at 'cs' (context switch) column spiking to 500,000+\n"
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         'Deploy **PgBouncer** in **Transaction Pooling** mode:\n'
         '```ini\n'
         '# pgbouncer.ini\n'
         '[databases]\n'
         'mydb = host=127.0.0.1 port=5432 dbname=mydb pool_size=50\n'
         '\n'
         '[pgbouncer]\n'
         'pool_mode = transaction\n'
         'max_client_conn = 5000\n'
         'default_pool_size = 50\n'
         '```\n'
         '5,000 application workers connect to PgBouncer. PgBouncer multiplexes their active queries into a tight, '
         'optimal pool of only 50 true Postgres connections, keeping CPU utilization focused on query execution.'),
        ('Online DDL Table Lock Timeout from Unindexed Migration',
         "-- Production table 'invoices' contains 80,000,000 rows\n"
         "-- Application runs 2,000 queries per second on 'invoices'\n"
         '\n'
         '-- Migration script executed during peak hours:\n'
         'ALTER TABLE invoices ADD COLUMN tax_rate numeric NOT NULL DEFAULT 0.05;\n',
         'As soon as migration executes, all API requests freeze. Connection pool exhausts in 10 seconds. Database '
         'stops responding until the migration is manually killed.',
         ['What table lock level does `ALTER TABLE` acquire in PostgreSQL?',
          'Why does an `AccessExclusiveLock` wait in queue behind existing read queries and block all subsequent '
          'reads?',
          'How do you safely add columns, indexes, and constraints using `lock_timeout` and zero-downtime DDL '
          'patterns?'],
         '**Root Cause:**\n'
         '`ALTER TABLE` requires an `AccessExclusiveLock`, which conflicts with every other lock level, including '
         'simple `SELECT` queries (`AccessShareLock`). Even though adding a column with a constant default is '
         'metadata-only in Postgres 11+, the DDL statement cannot proceed until all active queries running on '
         '`invoices` finish. While `ALTER TABLE` waits in the lock queue for long-running queries to complete, **all '
         'subsequent incoming SELECT queries queue up behind the DDL lock**, causing total connection pool exhaustion '
         'and a cascading outage.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check lock queue in `pg_locks`:\n'
         '   ```sql\n'
         '   SELECT pid, granted, mode, query \n'
         '   FROM pg_locks l \n'
         '   JOIN pg_stat_activity a ON l.pid = a.pid \n'
         "   WHERE relation = 'invoices'::regclass;\n"
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Always set a strict `lock_timeout`:**\n'
         '   ```sql\n'
         "   SET lock_timeout = '2s';\n"
         '   ALTER TABLE invoices ADD COLUMN tax_rate numeric DEFAULT 0.05;\n'
         '   ```\n'
         '   If the lock cannot be acquired within 2 seconds, the DDL fails immediately without backlogging user '
         'traffic.\n'
         '2. **Multi-step Zero-Downtime Migration Pattern:**\n'
         '   - Step 1: Add column without `NOT NULL` (instantaneous metadata change):\n'
         '     ```sql\n'
         '     ALTER TABLE invoices ADD COLUMN tax_rate numeric DEFAULT 0.05;\n'
         '     ```\n'
         '   - Step 2: Add `NOT NULL` constraint as `NOT VALID`:\n'
         '     ```sql\n'
         '     ALTER TABLE invoices ADD CONSTRAINT chk_tax_not_null CHECK (tax_rate IS NOT NULL) NOT VALID;\n'
         '     ```\n'
         '   - Step 3: Validate constraint asynchronously without locking:\n'
         '     ```sql\n'
         '     ALTER TABLE invoices VALIDATE CONSTRAINT chk_tax_not_null;\n'
         '     ```'),
        ('Replication Lag Storm During Bulk Purge Deleting 10M Rows',
         '-- Nightly cleanup script executing on Primary:\n'
         "DELETE FROM audit_events WHERE created_at < NOW() - INTERVAL '90 days';\n"
         '-- Deleted 12,000,000 rows in a single statement!\n',
         'On the primary, the query finishes in 90 seconds. On the standby replica, replication lag climbs to 4 hours. '
         'Read-traffic routed to the replica serves stale data. Standby disk I/O saturates at 100%.',
         ['Why does a single monolithic `DELETE` cause massive replication lag on streaming replicas?',
          'What is `max_standby_streaming_delay` in PostgreSQL, and how does query cancellation occur on standby?',
          'How should large purges be batched in small chunks or handled via table partitioning (`DROP TABLE`)?'],
         '**Root Cause:**\n'
         'Deleting 12,000,000 rows generates gigabytes of WAL records containing tombstone records, index deletions, '
         'and vacuum prerequisites. The primary can apply changes using multiple parallel worker threads or '
         'asynchronous I/O, but the standby replica applies WAL sequentially using a single startup process thread '
         '(`Startup`). When user queries on the replica access pages being modified by the WAL replay, a conflict '
         'occurs. If `max_standby_streaming_delay` expires, the replica either cancels user queries or pauses '
         'replication, causing lag to spiral out of control.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check replication lag on replica:\n'
         '   ```sql\n'
         '   SELECT pg_size_pretty(pg_wal_lsn_diff(pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn())) AS '
         'replay_lag;\n'
         '   ```\n'
         '2. Check replication conflicts:\n'
         '   ```sql\n'
         '   SELECT * FROM pg_stat_database_conflicts;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Batching the Purge:** Delete in small batches of 5,000 rows with a sleep interval to allow the replica '
         'startup process to keep up:\n'
         '   ```python\n'
         '   while True:\n'
         '       deleted = db.execute("""\n'
         '           WITH cte AS (\n'
         '               SELECT id FROM audit_events \n'
         "               WHERE created_at < NOW() - INTERVAL '90 days'\n"
         '               LIMIT 5000\n'
         '           )\n'
         '           DELETE FROM audit_events WHERE id IN (TABLE cte)\n'
         '           RETURNING id;\n'
         '       """).rowcount\n'
         '       if deleted == 0:\n'
         '           break\n'
         '       time.sleep(0.1)  # Throttle WAL generation\n'
         '   ```\n'
         '2. **Declarative Partitioning:** Partition `audit_events` by month. Dropping an old month (`DROP TABLE '
         'audit_events_2025_10`) is instantaneous, produces zero WAL row tombstones, and causes 0ms replication lag.'),
        ('Split-Brain Automated Failover from Transient Network Blip',
         '# Custom HA Failover Daemon monitoring PostgreSQL Primary\n'
         'while True:\n'
         '    try:\n'
         '        ping_primary()\n'
         '    except TimeoutError:\n'
         '        promote_standby()  # pg_ctl promote on replica!\n'
         '        break\n'
         '    time.sleep(1)\n',
         'A 3-second network switch hiccup causes the failover daemon to promote the replica. The old primary never '
         'died and continues taking writes from clients on switch A. The newly promoted standby accepts writes from '
         'switch B. The database is in split-brain with diverged WAL timelines.',
         ['What is split-brain in database high-availability, and why is timeline divergence disastrous?',
          'What is STONITH / Fencing, and why is a quorum consensus mandatory for automated failover?',
          'How do Patroni and Raft/Etcd guarantee mutual exclusion during automated leader election?'],
         '**Root Cause:**\n'
         'A naive failover daemon that promotes a standby based solely on local ping timeouts without **fencing '
         '(STONITH - Shoot The Other Node In The Head)** creates a dual-primary split-brain. Once the standby is '
         'promoted, it branches onto a new PostgreSQL timeline (Timeline 2). Meanwhile, the old primary on Timeline 1 '
         'continues accepting writes from any clients still connected to it. Because both nodes accepted different '
         'writes at the same LSN positions, their physical data files permanently diverge and cannot be '
         're-synchronized without manual hex-level data loss reconciliation.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check timeline status:\n'
         '   ```bash\n'
         '   pg_controldata /var/lib/postgresql/data | grep "Latest checkpoint\'s TimeLineID"\n'
         '   ```\n'
         '   If Primary shows Timeline 1 and Standby shows Timeline 2, split-brain has occurred.\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Never write custom failover scripts:** Use enterprise consensus-backed HA managers such as **Patroni** '
         '(backed by etcd/Consul) or **pg_auto_failover**.\n'
         '2. **DCS (Distributed Consensus Store) Leases:** In Patroni, the leader acquires a TTL lease in etcd. If the '
         'leader loses network connectivity to etcd, it demotes itself to read-only before its lease expires.\n'
         '3. **Fencing (STONITH):** Ensure power management (IPMI/AWS API) forcefully terminates the old primary '
         'instance before the standby is permitted to promote.')],
 '24': [('Dual-Write Data Drift Between Postgres and Elasticsearch',
         '# E-Commerce Order Processing Service\n'
         '@app.post("/orders")\n'
         'def create_order(order_data: dict):\n'
         '    # Step 1: Save order to PostgreSQL\n'
         '    order = db.save_order(order_data)\n'
         '    \n'
         '    # Step 2: Push to Elasticsearch for search indexing\n'
         '    es.index(index="orders", id=order.id, document=order.to_dict())\n'
         '    \n'
         '    return {"status": "success", "order_id": order.id}\n',
         'Over 3 months, 2,400 orders exist in PostgreSQL but are completely missing in Elasticsearch. When '
         'Elasticsearch experienced a 5-second network timeout, Step 1 committed, Step 2 threw an exception, and state '
         'permanently drifted.',
         ['What is the fundamental flaw of the dual-write anti-pattern across disparate data stores?',
          'Why cannot a distributed transaction (2PC) be cleanly executed between Postgres and Elasticsearch?',
          'How does the Transactional Outbox Pattern with Change Data Capture (CDC / Debezium) guarantee eventual '
          'consistency?'],
         '**Root Cause:**\n'
         'The **dual-write pattern** lacks atomicity. PostgreSQL and Elasticsearch are separate storage systems '
         'without a shared transaction coordinator. If Step 1 succeeds and Step 2 fails (network glitch, ES node '
         'restart, or application crash before Step 2), the data exists in the database but never reaches the search '
         'index. Conversely, if Step 2 were executed first and Step 1 failed, ghost data would exist in the search '
         'engine.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Run reconciliation script comparing record counts and IDs between Postgres and Elasticsearch:\n'
         '   ```sql\n'
         '   SELECT count(*) FROM orders;\n'
         '   ```\n'
         '   vs `GET /orders/_count`.\n'
         '2. Inspect application error logs for unhandled Elasticsearch timeout exceptions.\n'
         '\n'
         '**Production Fix:**\n'
         'Implement the **Transactional Outbox Pattern** with **CDC (Debezium)**:\n'
         '1. When saving the order in PostgreSQL, write an outbox event in the same atomic transaction:\n'
         '   ```sql\n'
         '   BEGIN;\n'
         '   INSERT INTO orders (...) VALUES (...);\n'
         "   INSERT INTO outbox_events (aggregate_type, aggregate_id, payload) VALUES ('order', order_id, ...);\n"
         '   COMMIT;\n'
         '   ```\n'
         "2. Debezium reads PostgreSQL's write-ahead log (WAL) via logical decoding and publishes events to Apache "
         'Kafka.\n'
         '3. A consumer reads Kafka and indexes documents into Elasticsearch with idempotent upserts (`PUT '
         '/orders/_doc/{id}`). This guarantees **at-least-once delivery** with zero data loss.'),
        ('Cache Stampede (Thundering Herd) on High-Traffic Key Expiration',
         'def get_homepage_recommendations(category_id: str):\n'
         '    cache_key = f"recs:{category_id}"\n'
         '    data = redis_client.get(cache_key)\n'
         '    \n'
         '    if data is None:\n'
         '        # Cache miss: Run complex multi-join SQL query taking 800ms\n'
         '        data = db.query_heavy_recommendations(category_id)\n'
         '        redis_client.setex(cache_key, 300, json.dumps(data)) # TTL = 5 mins\n'
         '        return data\n'
         '        \n'
         '    return json.loads(data)\n',
         'Every 5 minutes (exact cache TTL expiration), database CPU shoots to 100% and crashes. 5,000 concurrent '
         'requests arrive at the exact instant the cache expires, all executing the 800ms query simultaneously.',
         ['What is a Cache Stampede (Thundering Herd), and why does simple TTL expiration trigger it?',
          'What is Probabilistic Early Expiration (XFetch algorithm)?',
          'How can distributed mutex locking (Redis SETNX lock) protect the backing database?'],
         '**Root Cause:**\n'
         'A **cache stampede** occurs when a highly requested cache entry expires. During the 800ms window where the '
         'key is absent and being recomputed by the database, all 5,000 incoming requests observe `data is None`. '
         'Instead of 1 request updating the cache and 4,999 reading the cached result, all 5,000 requests execute the '
         'expensive database query in parallel, overwhelming connection pools and knocking the database offline.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check Postgres active queries during stampede:\n'
         '   ```sql\n'
         "   SELECT count(*), query FROM pg_stat_activity WHERE state = 'active' GROUP BY query;\n"
         '   -- 500 identical recommendation queries running simultaneously.\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '- **Approach 1 (Distributed Locking with Mutex):**\n'
         '  Only 1 worker computes the value; others wait or return stale data:\n'
         '  ```python\n'
         '  if data is None:\n'
         '      # Acquire lock for 5 seconds\n'
         '      if redis_client.set(f"lock:{cache_key}", "1", nx=True, ex=5):\n'
         '          try:\n'
         '              data = db.query_heavy_recommendations(category_id)\n'
         '              redis_client.setex(cache_key, 300, json.dumps(data))\n'
         '          finally:\n'
         '              redis_client.delete(f"lock:{cache_key}")\n'
         '      else:\n'
         '          time.sleep(0.05)\n'
         '          return get_homepage_recommendations(category_id)\n'
         '  ```\n'
         '- **Approach 2 (XFetch Probabilistic Early Expiration):**\n'
         '  Recompute the cache in the background *before* it expires based on $\x08eta \times \\delta \times \\ln(\t'
         'ext{random}())$.'),
        ('Out-of-Order Change Data Capture (CDC) Event Replay Overwrite',
         '# Kafka Consumer updating Read Model in MongoDB from CDC topic\n'
         'def process_cdc_event(message):\n'
         '    event = json.loads(message.value)\n'
         "    order_id = event['order_id']\n"
         "    new_status = event['status']\n"
         '    \n'
         '    # Direct overwrite:\n'
         '    mongo_db.orders.update_one(\n'
         '        {"_id": order_id},\n'
         '        {"$set": {"status": new_status, "updated_at": event[\'timestamp\']}},\n'
         '        upsert=True\n'
         '    )\n',
         "An order was CANCELLED by the user. However, the database shows status = 'SHIPPED'. Auditing confirms the "
         'user cancelled the order AFTER it was shipped, but MongoDB shows SHIPPED.',
         ['Why can messages in a distributed streaming platform (Kafka) arrive or be processed out of order?',
          'How does Kafka partitioning affect message ordering guarantees?',
          'How do version checks / optimistic concurrency control prevent stale events from clobbering newer state?'],
         '**Root Cause:**\n'
         'In distributed systems, network retransmissions, multiple consumer threads, or consumer rebalancing can '
         'cause CDC events to arrive out of order. If the events `Status: SHIPPED (seq=1)` and `Status: CANCELLED '
         '(seq=2)` are processed concurrently or re-delivered, the consumer may process `seq=2` first and `seq=1` '
         'second. Without version checking, the older `SHIPPED` event overwrites the newer `CANCELLED` event, '
         'corrupting the read model.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Check Kafka consumer group lag and partition assignments:\n'
         '   ```bash\n'
         '   kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group cdc_mongo_consumers\n'
         '   ```\n'
         '2. Verify if partition key was set on the message (missing partition key routes messages randomly across '
         'partitions).\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Ensure Kafka Message Keying:** Always use the primary entity key (e.g. `order_id`) as the Kafka message '
         'key so all events for the same order are strictly routed to the **same partition**.\n'
         '2. **Optimistic Version Filtering in Consumer:** Only update if the incoming event has a greater '
         'version/timestamp than what is currently stored:\n'
         '   ```python\n'
         '   mongo_db.orders.update_one(\n'
         '       {\n'
         '           "_id": order_id,\n'
         '           "version": {"$lt": event[\'version\']}  # Only overwrite if older\n'
         '       },\n'
         '       {\n'
         '           "$set": {\n'
         '               "status": new_status,\n'
         '               "version": event[\'version\'],\n'
         '               "updated_at": event[\'timestamp\']\n'
         '           }\n'
         '       },\n'
         '       upsert=True\n'
         '   )\n'
         '   ```'),
        ('Distributed Transaction Failure in Polyglot Workflow Without Saga',
         '# Microservices Architecture: OrderService, InventoryService, PaymentService\n'
         'def checkout(user_id, cart):\n'
         '    # Step 1: Deduct inventory in Postgres (InventoryService)\n'
         '    inv_res = requests.post("http://inventory-service/deduct", json=cart)\n'
         '    \n'
         '    # Step 2: Charge credit card via Stripe (PaymentService)\n'
         '    pay_res = requests.post("http://payment-service/charge", json={"user": user_id, "amount": cart.total})\n'
         '    \n'
         '    # Step 3: Insert order into Postgres (OrderService)\n'
         '    order_res = requests.post("http://order-service/orders", json=cart)\n'
         '    \n'
         '    return {"status": "complete"}\n',
         'Step 1 deducted 5 items from inventory. Step 2 charged the customer $500. Step 3 timed out with HTTP 504. '
         'The customer was charged, inventory was lost, but no order exists in the system.',
         ['Why does chaining synchronous HTTP calls across microservices violate transaction atomicity?',
          'What is the difference between an Orchestrated Saga and a Choreographed Saga?',
          'How do compensating transactions and idempotency keys ensure system consistency?'],
         '**Root Cause:**\n'
         'In a polyglot microservice architecture, each service controls its own independent database. Chaining '
         'multiple synchronous HTTP requests lacks distributed atomicity. When Step 3 fails or times out, the changes '
         'committed in Step 1 (inventory reserved) and Step 2 (credit card charged) remain committed without automatic '
         'rollback, leaving the distributed system in an inconsistent, fractured state.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Inspect distributed traces (OpenTelemetry / Jaeger) for trace IDs with failing downstream spans.\n'
         '2. Check reconciliation logs between Payment transactions and Order database IDs.\n'
         '\n'
         '**Production Fix:**\n'
         'Implement the **Saga Pattern** (Orchestrated or Choreographed) with **Compensating Transactions** and '
         '**Idempotency Keys**:\n'
         '1. **Pass Idempotency Keys:** Ensure every call carries a unique `Idempotency-Key: {checkout_id}` so retries '
         'do not double-charge.\n'
         '2. **Compensating Transactions:** If Step 3 fails, the Saga Orchestrator executes compensating actions in '
         'reverse order:\n'
         '   - Call `PaymentService.refund(charge_id)`\n'
         '   - Call `InventoryService.release(cart_items)`\n'
         '3. Use workflow orchestrators like **Temporal** or **AWS Step Functions** to persist execution state durable '
         'across service crashes.'),
        ('Read-Your-Own-Writes Inconsistency on Asynchronous Read Replicas',
         '# Web Application\n'
         '@app.post("/update_profile")\n'
         'def update_profile(user_id: int, new_bio: str):\n'
         '    # Writes go to Primary database\n'
         '    primary_db.execute("UPDATE users SET bio = %s WHERE id = %s", (new_bio, user_id))\n'
         '    return redirect("/profile")\n'
         '\n'
         '@app.get("/profile")\n'
         'def view_profile(user_id: int):\n'
         '    # Reads go to Read Replica to offload primary\n'
         '    user = replica_db.query_one("SELECT * FROM users WHERE id = %s", (user_id,))\n'
         '    return render_template("profile.html", user=user)\n',
         "User updates their bio and clicks 'Save'. The browser immediately redirects to /profile, displaying their "
         'OLD bio. User repeatedly refreshes in confusion; after 3 seconds, the new bio suddenly appears.',
         ['What causes Read-Your-Own-Writes inconsistency in primary-replica database topologies?',
          'What is replication lag, and why is asynchronous replication non-zero latency?',
          'What architectural patterns (session-based primary routing, replica lag cookies, or write tracking) solve '
          'this?'],
         '**Root Cause:**\n'
         'In asynchronous replication, mutations committed on the Primary database are written to WAL and shipped over '
         'the network to the Read Replica. There is an inherent delay—**replication lag** (typically 10ms to '
         '2,000ms)—before the replica receives and applies the WAL. When the web application immediately redirects the '
         'user to `/profile` and routes the read to the replica, the replica has not yet processed the update, serving '
         'the stale pre-update record.\n'
         '\n'
         '**Diagnostic Commands:**\n'
         '1. Measure replication lag on the replica:\n'
         '   ```sql\n'
         '   SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) AS lag_seconds;\n'
         '   ```\n'
         '\n'
         '**Production Fix:**\n'
         '1. **Session-Level Sticky Primary Routing:** If a user performs a write, route all subsequent reads from '
         'that specific user to the **Primary** database for a window of time (e.g. 5 seconds):\n'
         '   ```python\n'
         "   session['last_write_timestamp'] = time.time()\n"
         '   \n'
         '   def get_db():\n'
         "       if time.time() - session.get('last_write_timestamp', 0) < 5:\n"
         '           return primary_db\n'
         '       return replica_db\n'
         '   ```\n'
         '2. **LSN-Based Routing (Causal Consistency):** Store the commit LSN of the write in a client cookie. When '
         'querying the replica, ensure the replica has replayed up to that LSN (`pg_last_wal_replay_lsn() >= '
         'cookie_lsn`); if not, route to primary or wait.')]}

